import type { MyTasksTaskRow } from "@/lib/agent/taskAssist/myTasksTaskTypes";
import { conversationChannelLabel } from "@/lib/communications/v2/commandCenterViewModel";

export function buildWorkItemCommunicationsProvenanceChain(task: MyTasksTaskRow): string[] {
    const family = task.communication_family_label?.trim() || task.entity_label?.trim() || "Thread";
    const lane = task.communication_lane?.replace(/_/g, " ") ?? "needs reply";
    const laneLabel = lane.replace(/\b\w/g, (c) => c.toUpperCase());
    return ["Generated by Communications", family, laneLabel];
}

export function formatWorkItemCommunicationsProvenanceChain(chain: string[]): string {
    return chain.join(" → ");
}

export function buildWorkItemCommunicationsSummary(task: MyTasksTaskRow): string {
    const chain = formatWorkItemCommunicationsProvenanceChain(buildWorkItemCommunicationsProvenanceChain(task));
    const channel = conversationChannelLabel(task.communication_channel);
    const preview = task.communication_last_preview?.trim() || "Open in Communications to reply.";
    return `${chain} · ${channel} · ${preview}`;
}
