/**
 * Work Items V3 — Business Process provenance presentation over operational_tasks metadata.
 */

import { isBusinessProcessStageWorkTaskRow } from "@/lib/lifecycle/isBusinessProcessStageWorkTaskRow";
import type { MyTasksTaskRow } from "@/lib/agent/taskAssist/myTasksTaskTypes";
import { normalizeOperationalTaskTitleDisplay } from "@/lib/agent/taskAssist/normalizeOperationalTaskTitleDisplay";
import {
    resolveWorkItemBpDisplayLabel,
    WORK_ITEM_BP_FALLBACK_PROCESS_LABEL,
} from "@/lib/workItems/workItemBpDisplayLabel";

export type WorkItemBpLabelOptions = {
    processLabels?: Record<string, string>;
    stageLabels?: Record<string, string>;
    fallbackProcessLabel?: string;
};

function humanizeKey(key: string): string {
    const cleaned = key.replace(/[_-]+/g, " ").trim();
    if (!cleaned) return key;
    return cleaned.replace(/\b\w/g, (c) => c.toUpperCase());
}

export function resolveWorkItemProcessLabel(
    task: Pick<MyTasksTaskRow, "department_id">,
    options?: WorkItemBpLabelOptions,
): string {
    return resolveWorkItemBpDisplayLabel(
        task.department_id,
        options?.processLabels,
        options?.fallbackProcessLabel ?? WORK_ITEM_BP_FALLBACK_PROCESS_LABEL,
    );
}

export function resolveWorkItemStageLabel(
    task: Pick<MyTasksTaskRow, "lifecycle_stage_key">,
    options?: WorkItemBpLabelOptions,
): string | null {
    const stage = task.lifecycle_stage_key?.trim();
    if (!stage) return null;
    return options?.stageLabels?.[stage] ?? humanizeKey(stage);
}

export function buildWorkItemBpProvenanceChain(
    task: MyTasksTaskRow,
    options?: WorkItemBpLabelOptions,
): string[] {
    if (!isBusinessProcessStageWorkTaskRow(task)) return [];

    const chain: string[] = ["Generated by Business Process"];
    const processLabel = resolveWorkItemProcessLabel(task, options);
    if (processLabel !== "General work") chain.push(processLabel);

    const stageLabel = resolveWorkItemStageLabel(task, options);
    if (stageLabel) chain.push(stageLabel);

    const workLabel =
        normalizeOperationalTaskTitleDisplay(task.title)?.trim()
        || (task.work_definition_key?.trim() ? humanizeKey(task.work_definition_key) : null);
    if (workLabel) chain.push(workLabel);

    return chain;
}

export function formatWorkItemBpProvenanceChain(chain: string[]): string {
    return chain.join(" → ");
}

export function buildWorkItemBpBreadcrumb(
    task: MyTasksTaskRow,
    options?: WorkItemBpLabelOptions & { recordLabel?: string | null },
): string {
    const chain = buildWorkItemBpProvenanceChain(task, options);
    if (chain.length > 0) {
        const record = options?.recordLabel?.trim();
        return record ? `${formatWorkItemBpProvenanceChain(chain)} → ${record}` : formatWorkItemBpProvenanceChain(chain);
    }
    return "";
}

export function buildWorkItemProcessLabelsFromTasks(
    tasks: Pick<MyTasksTaskRow, "department_id">[],
    fallbackProcessLabel = WORK_ITEM_BP_FALLBACK_PROCESS_LABEL,
): Record<string, string> {
    const labels: Record<string, string> = {};
    for (const task of tasks) {
        const dept = task.department_id?.trim();
        if (!dept || labels[dept]) continue;
        labels[dept] = resolveWorkItemBpDisplayLabel(dept, labels, fallbackProcessLabel);
    }
    return labels;
}
