import type { MyTasksTaskRow } from "@/lib/agent/taskAssist/myTasksTaskTypes";

export function buildWorkItemProcessingProvenanceChain(task: MyTasksTaskRow): string[] {
    const caseLabel = task.processing_source_label?.trim() || "Processing case";
    const lane = task.processing_lane?.replace(/_/g, " ") ?? "needs review";
    return ["Generated by Processing", caseLabel, lane.replace(/\b\w/g, (c) => c.toUpperCase())];
}

export function formatWorkItemProcessingProvenanceChain(chain: string[]): string {
    return chain.join(" → ");
}
