#!/usr/bin/env node
/**
 * Write web/.env.local for isolated certification stack (gitignored).
 * Reads `supabase status -o env` from project root.
 */
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const envOut = resolve(root, "web/.env.local");

const raw = execSync("supabase status -o env", { cwd: root, encoding: "utf8" });
const vars = {};
for (const line of raw.split("\n")) {
    const m = line.match(/^([A-Z0-9_]+)="(.*)"/);
    if (m) vars[m[1]] = m[2];
}

const apiUrl = vars.API_URL;
if (!apiUrl || !apiUrl.includes(":55321")) {
    console.error("Refusing to write .env.local: isolated cert stack (55321) not running.");
    process.exit(1);
}
if (apiUrl.includes("54321")) {
    console.error("Refusing: API URL points at forbidden port 54321.");
    process.exit(1);
}

const lines = [
    "# Generated by scripts/processing/writeCertEnvLocal.mjs — do not commit",
    `NEXT_PUBLIC_SUPABASE_URL=${apiUrl}`,
    `SUPABASE_URL=${apiUrl}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${vars.ANON_KEY}`,
    `SUPABASE_SERVICE_ROLE_KEY=${vars.SERVICE_ROLE_KEY}`,
    `PROCESSING_LOCAL_CERT_ENABLED=true`,
    `PROCESSING_LOCAL_CERT_ALLOW_HTTP=true`,
    `PROCESSING_LOCAL_CERT_DATABASE_URL=${vars.DB_URL}`,
    `NEXT_PUBLIC_APP_URL=http://127.0.0.1:3000`,
    "",
];
writeFileSync(envOut, lines.join("\n"));
console.log(`Wrote ${envOut} targeting ${apiUrl}`);
