import { describe, expect, it } from "vitest";

import type { MyTasksTaskRow } from "@/lib/agent/taskAssist/myTasksTaskTypes";
import type { ConversationSummary } from "@/lib/communications/v2/commandCenterViewModel";
import { buildMyTasksPresentationLabels } from "@/lib/agent/taskAssist/myTasksPresentationLabels";
import {
    communicationWorkItemId,
    conversationRequiresReplyForWorkItemProjection,
    mapCommunicationThreadToWorkItemRow,
    mapCommunicationsQueueToWorkItemRows,
    parseCommunicationThreadIdFromWorkItemId,
} from "@/lib/workItems/mapCommunicationThreadToWorkItemRow";
import { buildWorkItemBreadcrumb } from "@/lib/workItems/mapWorkItemQueueRow";
import {
    applyWorkItemQueueScope,
    countTasksForSource,
    resolveWorkItemQueueEmptyState,
    taskMatchesSource,
} from "@/lib/workItems/workItemQueueScope";
import { buildWorkItemCommunicationsProvenanceChain } from "@/lib/workItems/workItemCommunicationsProvenance";
import { deriveWorkItemsProcessGroups } from "@/lib/agent/taskAssist/myTasksProcessGroups";

function needsReplyConversation(overrides: Partial<ConversationSummary> = {}): ConversationSummary {
    return {
        id: "thread-1",
        family_label: "Nguyen Family",
        topic_label: "Enrollment question",
        channel: "sms",
        attention_state: "needs_response",
        scope_status: "resolved",
        assignment_state: "unassigned",
        last_message_preview: "Can we schedule a tour?",
        last_message_at: "2026-07-10T18:00:00.000Z",
        last_activity_at: "2026-07-10T18:00:00.000Z",
        ...overrides,
    } as ConversationSummary;
}

describe("Work Items Communications convergence", () => {
    it("projects authoritative Needs Reply thread once with stable synthetic id", () => {
        const rows = mapCommunicationsQueueToWorkItemRows([
            needsReplyConversation(),
            needsReplyConversation({ id: "thread-1" }),
        ]);
        expect(rows).toHaveLength(1);
        expect(rows[0]?.id).toBe(communicationWorkItemId("thread-1"));
        expect(rows[0]?.is_communications_projection).toBe(true);
        expect(parseCommunicationThreadIdFromWorkItemId(rows[0]!.id)).toBe("thread-1");
    });

    it("does not project unread-only or resolved threads", () => {
        expect(
            conversationRequiresReplyForWorkItemProjection(
                needsReplyConversation({ attention_state: null, unread_count: 3 }),
            ),
        ).toBe(false);
        expect(
            mapCommunicationThreadToWorkItemRow(
                needsReplyConversation({ attention_state: "resolved" }),
            ),
        ).toBeNull();
    });

    it("uses authoritative assignee and does not fabricate operational_tasks", () => {
        const row = mapCommunicationThreadToWorkItemRow(
            needsReplyConversation({
                assignment_state: "assigned",
                assigned_user_id: "user-9",
            }),
        );
        expect(row?.assigned_to_user_id).toBe("user-9");
        expect(row?.source).toBe("communications");
        expect(row?.communication_lane).toBe("needs_reply");
    });

    it("filters Communications source and Mine intersection truthfully", () => {
        const mineTask: MyTasksTaskRow = {
            ...(mapCommunicationThreadToWorkItemRow(
                needsReplyConversation({ assignment_state: "assigned", assigned_user_id: "user-1" }),
            ) as MyTasksTaskRow),
        };
        const unassignedTask: MyTasksTaskRow = {
            ...(mapCommunicationThreadToWorkItemRow(needsReplyConversation()) as MyTasksTaskRow),
        };
        expect(taskMatchesSource(mineTask, "communications")).toBe(true);
        expect(countTasksForSource([mineTask, unassignedTask], "communications")).toBe(2);

        const groups = deriveWorkItemsProcessGroups([], { fallbackProcessLabel: "Enrollment" });
        const mineScoped = applyWorkItemQueueScope(
            [mineTask, unassignedTask],
            { folder: "all_work", view: "mine", source: "communications", sort: "due_date" },
            groups,
            "user-1",
        );
        expect(mineScoped).toHaveLength(1);
        expect(mineScoped[0]?.id).toBe(mineTask.id);

        const mineEmpty = resolveWorkItemQueueEmptyState(
            { folder: "all_work", view: "mine", source: "communications", sort: "due_date" },
        );
        expect(mineEmpty.message).toContain("Communications");
    });

    it("renders Communications provenance without exposing raw UUID labels", () => {
        const row = mapCommunicationThreadToWorkItemRow(needsReplyConversation())!;
        const chain = buildWorkItemCommunicationsProvenanceChain(row);
        expect(chain).toEqual(["Generated by Communications", "Nguyen Family", "Needs Reply"]);
        const breadcrumb = buildWorkItemBreadcrumb(row, buildMyTasksPresentationLabels({}), {}, {});
        expect(breadcrumb).toContain("Generated by Communications");
        expect(breadcrumb).not.toContain("thread-1");
    });

    it("clears resolved projections from active Communications counts", () => {
        const active = mapCommunicationThreadToWorkItemRow(needsReplyConversation());
        const resolved = mapCommunicationThreadToWorkItemRow(
            needsReplyConversation({ id: "thread-2", attention_state: "resolved" }),
        );
        expect(active).not.toBeNull();
        expect(resolved).toBeNull();
        expect(countTasksForSource([active!], "communications")).toBe(1);
    });
});
