import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import type { MyTasksTaskRow } from "@/lib/agent/taskAssist/myTasksTaskTypes";
import {
    buildWorkItemBpProvenanceChain,
    buildWorkItemProcessLabelsFromTasks,
    formatWorkItemBpProvenanceChain,
} from "@/lib/workItems/workItemBpProvenance";
import { buildWorkItemBreadcrumb, buildWorkItemBosSummary, mapWorkItemQueueRow } from "@/lib/workItems/mapWorkItemQueueRow";
import { buildMyTasksPresentationLabels } from "@/lib/agent/taskAssist/myTasksPresentationLabels";

const currentWorkCard = join(
    dirname(fileURLToPath(import.meta.url)),
    "../../components/admin/focusPanel/cards/CurrentWorkCard.tsx",
);
const myTasksModal = join(dirname(fileURLToPath(import.meta.url)), "../../app/adminV2/components/MyTasksModal.tsx");
const navigation = join(dirname(fileURLToPath(import.meta.url)), "../../lib/workItems/workItemsNavigation.ts");

function bpTask(overrides: Partial<MyTasksTaskRow> = {}): MyTasksTaskRow {
    return {
        id: overrides.id ?? "task-bp-1",
        title: overrides.title ?? "Contact Family",
        description: overrides.description ?? "Follow up after tour",
        due_at: overrides.due_at ?? "2026-07-20T16:00:00.000Z",
        status: overrides.status ?? "open",
        source: overrides.source ?? "manual",
        entity_id: overrides.entity_id ?? "opp-1",
        entity_type: overrides.entity_type ?? "opportunities",
        assigned_to_user_id: overrides.assigned_to_user_id ?? "u1",
        created_at: overrides.created_at ?? "2026-07-10T16:00:00.000Z",
        entity_label: overrides.entity_label ?? "Jordan Family Lead",
        department_id: overrides.department_id ?? "enrollment",
        lifecycle_stage_key: overrides.lifecycle_stage_key ?? "tour_scheduled",
        lifecycle_provenance: overrides.lifecycle_provenance ?? "lifecycle_template",
        work_definition_key: overrides.work_definition_key ?? "contact_family",
    };
}

describe("Work Items BP convergence", () => {
    it("builds explicit Business Process provenance chain", () => {
        const chain = buildWorkItemBpProvenanceChain(bpTask(), {
            processLabels: { enrollment: "Enrollment" },
            stageLabels: { tour_scheduled: "Tour Scheduled" },
        });
        expect(chain[0]).toBe("Generated by Business Process");
        expect(formatWorkItemBpProvenanceChain(chain)).toContain("Enrollment");
        expect(formatWorkItemBpProvenanceChain(chain)).toContain("Tour Scheduled");
        expect(formatWorkItemBpProvenanceChain(chain)).toContain("Contact Family");
    });

    it("maps BP work rows with BP badge and provenance breadcrumb", () => {
        const presentation = buildMyTasksPresentationLabels({ opportunities: { singular: "Lead", plural: "Leads" } });
        const row = mapWorkItemQueueRow(bpTask(), {
            presentation,
            entityLabels: { opportunities: { singular: "Lead", plural: "Leads" } },
            labelOptions: { processLabels: { enrollment: "Enrollment" } },
        });
        expect(row.badge).toBe("BP");
        expect(row.breadcrumb).toContain("Generated by Business Process");
        expect(row.breadcrumb).toContain("Enrollment");
        expect(row.trailingMeta).toBe("Business Process");
    });

    it("derives process labels from task metadata", () => {
        const labels = buildWorkItemProcessLabelsFromTasks([
            bpTask(),
            bpTask({ department_id: "compliance_ops" }),
        ]);
        expect(labels.enrollment).toBe("Enrollment");
        expect(labels.compliance_ops).toBe("Compliance Ops");
    });

    it("uses BP provenance in breadcrumb and BOS summary", () => {
        const task = bpTask();
        const presentation = buildMyTasksPresentationLabels({});
        const labels = { processLabels: { enrollment: "Enrollment" } };
        const breadcrumb = buildWorkItemBreadcrumb(task, presentation, {}, labels);
        const summary = buildWorkItemBosSummary(task, labels);
        expect(breadcrumb).toContain("Tour Scheduled");
        expect(summary).toContain("Generated by Business Process");
    });

    it("wires cross-navigation contracts", () => {
        expect(readFileSync(navigation, "utf8")).toContain("ADMIN_V2_OPEN_WORK_ITEMS_TASK");
        expect(readFileSync(navigation, "utf8")).toContain("ADMIN_V2_OPPORTUNITY_FOCUS_CURRENT_WORK");
        expect(readFileSync(myTasksModal, "utf8")).toContain("ADMIN_V2_OPEN_WORK_ITEMS_TASK");
        expect(readFileSync(currentWorkCard, "utf8")).toContain("ViewInWorkItemsLink");
        expect(readFileSync(currentWorkCard, "utf8")).toContain("ADMIN_V2_OPPORTUNITY_FOCUS_CURRENT_WORK");
    });
});
