import { describe, expect, it } from "vitest";

import type { EntityLabelsMap } from "@/contexts/EntityLabelsContext";
import { buildMyTasksPresentationLabels } from "@/lib/agent/taskAssist/myTasksPresentationLabels";
import type { MyTasksTaskRow } from "@/lib/agent/taskAssist/myTasksTaskTypes";
import {
    buildWorkItemBosSummary,
    buildWorkItemBreadcrumb,
    mapWorkItemQueueRow,
} from "@/lib/workItems/mapWorkItemQueueRow";
import { WORK_ITEM_FOLDER_DEFS, WORK_ITEM_VIEW_DEFS } from "@/lib/workItems/workItemQueueScope";

function task(overrides: Partial<MyTasksTaskRow> = {}): MyTasksTaskRow {
    return {
        id: overrides.id ?? "task-1",
        title: overrides.title ?? "Follow up with household",
        description: overrides.description ?? "Confirm next steps",
        due_at: overrides.due_at ?? "2026-07-20T16:00:00.000Z",
        status: overrides.status ?? "open",
        source: overrides.source ?? "task_assist",
        entity_id: overrides.entity_id ?? "opp-1",
        entity_type: overrides.entity_type ?? "opportunities",
        assigned_to_user_id: overrides.assigned_to_user_id ?? "u1",
        created_at: overrides.created_at ?? "2026-07-10T16:00:00.000Z",
        entity_label: overrides.entity_label ?? "Jordan Family Lead",
        household_label: overrides.household_label ?? "Jordan Household",
        assignee_label: overrides.assignee_label ?? "Kelly Operator",
        department_id: overrides.department_id,
        lifecycle_stage_key: overrides.lifecycle_stage_key,
        lifecycle_provenance: overrides.lifecycle_provenance,
        work_definition_key: overrides.work_definition_key,
    };
}

describe("work item queue foundations", () => {
    const entityLabels: EntityLabelsMap = {
        opportunities: { singular: "Lead", plural: "Leads" },
    };
    const presentation = buildMyTasksPresentationLabels(entityLabels);

    it("keeps user-facing work item terminology labels", () => {
        expect(WORK_ITEM_FOLDER_DEFS.find((d) => d.key === "all_work")?.label).toBe("All Work");
        // R14: the KEY stays `mine`; the visible copy names the scope, because the KPI band's
        // assignment metric sits on the same screen and is a different population.
        expect(WORK_ITEM_VIEW_DEFS.find((d) => d.key === "mine")?.label).toBe("Assigned to me");
    });

    it("builds deterministic breadcrumb and BOS summary", () => {
        const row = task({
            department_id: "enrollment",
            lifecycle_stage_key: "tour_scheduled",
            lifecycle_provenance: "lifecycle_template",
            source: "manual",
        });
        const labels = { processLabels: { enrollment: "Enrollment" } };
        const breadcrumb = buildWorkItemBreadcrumb(row, presentation, entityLabels, labels);
        const summary = buildWorkItemBosSummary(row, labels);

        expect(breadcrumb).toContain("Generated by Business Process");
        expect(breadcrumb).toContain("Enrollment");
        expect(breadcrumb).toContain("Tour Scheduled");

        expect(summary).toContain("Generated by Business Process");
        expect(summary).toContain("Due");
    });

    it("maps MyTasks row to workspace queue row model", () => {
        const model = mapWorkItemQueueRow(task(), { presentation, entityLabels });

        expect(model.id).toBe("task-1");
        expect(model.badge).toBe("BOS");
        expect(model.completed).toBe(false);
        expect(model.breadcrumb.length).toBeGreaterThan(0);
        expect(model.dueOrTime?.startsWith("Due ")).toBe(true);
        expect(model.assigneeInitials).toBe("KO");
    });

    it("maps BP-generated rows to the BP badge, not the BOS one", () => {
        const model = mapWorkItemQueueRow(
            task({
                source: "manual",
                lifecycle_provenance: "lifecycle_template",
                department_id: "enrollment",
            }),
            { presentation, entityLabels, labelOptions: { processLabels: { enrollment: "Enrollment" } } },
        );
        expect(model.badge).toBe("BP");
    });

    /*
     * THE ROW CARRIES NO WAITING CLAIM AT ALL.
     *
     * `isWaiting` was `source === "task_assist" && open`, and the row rendered an amber **Waiting**
     * pill from it. That named a state this product does not have — the BOS badge beside it already
     * said, truthfully, where the row came from. The pill and the field are gone; this pins that a
     * BOS-sourced open row exposes no waiting flag for a pill to grow back from.
     */
    it("exposes no waiting flag on any row shape", () => {
        for (const row of [
            mapWorkItemQueueRow(task(), { presentation, entityLabels }),
            mapWorkItemQueueRow(task({ source: "manual" }), { presentation, entityLabels }),
        ]) {
            expect(row).not.toHaveProperty("isWaiting");
            expect(JSON.stringify(row)).not.toMatch(/waiting/i);
        }
    });
});
