/**
 * ORIGIN NEVER EXCEEDS THE EVIDENCE.
 *
 * Censused on deployed staging: job_id, schedule_id and subscription_id are set on ZERO of 125
 * rows, and every actorless charge is `source = charge_template`. So "Scheduled billing" is not a
 * conclusion the data can support, and `created_by = null` is the absence of a person rather than
 * the presence of a scheduler.
 */
import { describe, expect, it } from "vitest";
import {
    classifyChargeOrigin,
    describeChargeOrigin,
    type ChargeOriginEvidence,
} from "@/lib/financials/workspace/chargeOrigin";

const evidence = (over: Partial<ChargeOriginEvidence> = {}): ChargeOriginEvidence => ({
    createdBy: null, jobId: null, sourceChargeId: null, chargeTemplateId: null, metadataSource: null,
    ...over,
});

describe("precedence is by strength of evidence", () => {
    it("a recorded actor wins outright", () => {
        const o = classifyChargeOrigin(evidence({ createdBy: "u1", jobId: "j1", chargeTemplateId: "t1" }));
        expect(o).toEqual({ kind: "person", actorUserId: "u1" });
    });

    it("a human correction is still the human's charge", () => {
        /* sourceChargeId says what it RELATES to, not what raised it. */
        const o = classifyChargeOrigin(evidence({ createdBy: "u1", sourceChargeId: "c9" }));
        expect(o.kind).toBe("person");
    });

    it("the measured actorless shape resolves to the charge template", () => {
        /* Exactly the 18 rows the census found: no actor, no job, source=charge_template. */
        const o = classifyChargeOrigin(evidence({ metadataSource: "charge_template", chargeTemplateId: "t1" }));
        expect(o).toEqual({ kind: "charge_template", chargeTemplateId: "t1" });
    });

    it("falls to 'automatic' when nothing was recorded at all", () => {
        expect(classifyChargeOrigin(evidence())).toEqual({ kind: "automatic" });
    });

    it("names a billing run only when a job proves one", () => {
        expect(classifyChargeOrigin(evidence({ jobId: "j1" })).kind).toBe("billing_run");
        expect(classifyChargeOrigin(evidence()).kind, "and never otherwise").toBe("automatic");
    });
});

describe("the sentences never claim more than the evidence", () => {
    const all = [
        classifyChargeOrigin(evidence({ createdBy: "u1" })),
        classifyChargeOrigin(evidence({ jobId: "j1" })),
        classifyChargeOrigin(evidence({ sourceChargeId: "c1" })),
        classifyChargeOrigin(evidence({ metadataSource: "charge_template" })),
        classifyChargeOrigin(evidence()),
    ];

    it("never says Scheduled billing, Imported, or System generated by anything", () => {
        for (const o of all) {
            const s = describeChargeOrigin(o, "Kelly Kurzman");
            expect(s).not.toMatch(/scheduled billing/i);
            expect(s).not.toMatch(/imported/i);
            expect(s).not.toMatch(/system generated/i);
        }
    });

    it("names the person when identity knows them", () => {
        expect(describeChargeOrigin({ kind: "person", actorUserId: "u1" }, "Kelly Kurzman"))
            .toBe("Created by Kelly Kurzman");
    });

    it("says the name is unknown rather than printing an id in a person's place", () => {
        const s = describeChargeOrigin({ kind: "person", actorUserId: "u1" }, null);
        expect(s).not.toContain("u1");
        expect(s).toMatch(/not on file/);
    });

    it("stops at 'Created automatically' when nothing is recorded", () => {
        expect(describeChargeOrigin({ kind: "automatic" }, null)).toBe("Created automatically");
    });
});
