import type { MetricDefinitionCreateInput } from "@/lib/metrics/platform/metricDefinitionSchema";

/** Code-owned default enrollment metric templates (mirrors seed migration). */
export const DEFAULT_ENROLLMENT_METRIC_TEMPLATES: MetricDefinitionCreateInput[] = [
    {
        key: "tour_conversion_rate",
        label: "Tour Conversion %",
        description: "Share of scheduled tours that completed in the rolling period.",
        category: "enrollment",
        entity_scope: "org",
        source_type: "oip_adapter",
        source_key: "enrollment.tour_conversion_rate",
        aggregation: "rate",
        filter_config: { version: 1 },
        dimension_config: { version: 1 },
        default_period_config: { version: 1, kind: "rolling", days: 30 },
        unit: "percent",
        precision: 1,
        is_kpi: true,
        target_config: { version: 1, kind: "rate_min", targetMinRate: 0.65, direction: "higher_is_better" },
        threshold_config: { version: 1, healthyMinRate: 0.65, warningMinRate: 0.5 },
        status: "active",
        version: 1,
    },
    {
        key: "enrollment_rate",
        label: "Enrollment Rate",
        description: "Share of completed tours that converted to enrollment.",
        category: "enrollment",
        entity_scope: "org",
        source_type: "oip_adapter",
        source_key: "enrollment.tour_conversion_rate",
        aggregation: "rate",
        filter_config: { version: 1 },
        dimension_config: { version: 1 },
        default_period_config: { version: 1, kind: "rolling", days: 30 },
        unit: "percent",
        precision: 1,
        is_kpi: true,
        target_config: { version: 1, kind: "rate_min", targetMinRate: 0.4, direction: "higher_is_better" },
        threshold_config: { version: 1, healthyMinRate: 0.4, warningMinRate: 0.25 },
        status: "active",
        version: 1,
    },
    {
        key: "needs_attention_count",
        label: "Needs Attention Count",
        description: "Bounded snapshot of opportunities requiring operator attention.",
        category: "operational_health",
        entity_scope: "org",
        source_type: "oip_adapter",
        source_key: "ops.needs_attention_count",
        aggregation: "count",
        filter_config: { version: 1 },
        dimension_config: { version: 1 },
        default_period_config: { version: 1, kind: "rolling", days: 30 },
        unit: "count",
        precision: 0,
        is_kpi: true,
        target_config: { version: 1, kind: "count_max", targetMaxCount: 10, direction: "lower_is_better" },
        threshold_config: { version: 1, healthyMaxCount: 10, warningMaxCount: 25 },
        status: "active",
        version: 1,
    },
    {
        key: "forms_completion_rate",
        label: "Forms Completion %",
        description: "Share of form submissions completed in the rolling period.",
        category: "forms",
        entity_scope: "org",
        source_type: "oip_adapter",
        source_key: "forms.completion_rate",
        aggregation: "rate",
        filter_config: { version: 1 },
        dimension_config: { version: 1 },
        default_period_config: { version: 1, kind: "rolling", days: 30 },
        unit: "percent",
        precision: 1,
        is_kpi: true,
        target_config: { version: 1, kind: "rate_min", targetMinRate: 0.8, direction: "higher_is_better" },
        threshold_config: { version: 1, healthyMinRate: 0.8, warningMinRate: 0.6 },
        status: "active",
        version: 1,
    },
    {
        key: "lead_count",
        label: "Lead Count",
        description: "Count of new enrollment opportunities in the rolling period.",
        category: "enrollment",
        entity_scope: "org",
        source_type: "oip_adapter",
        source_key: "enrollment.lead_count",
        aggregation: "count",
        filter_config: { version: 1 },
        dimension_config: { version: 1 },
        default_period_config: { version: 1, kind: "rolling", days: 30 },
        unit: "count",
        precision: 0,
        is_kpi: false,
        status: "draft",
        version: 1,
    },
    {
        key: "tour_completed_count",
        label: "Completed Tours",
        description: "Count of tours completed in the rolling period.",
        category: "enrollment",
        entity_scope: "org",
        source_type: "oip_adapter",
        source_key: "enrollment.tour_completed_count",
        aggregation: "count",
        filter_config: { version: 1 },
        dimension_config: { version: 1 },
        default_period_config: { version: 1, kind: "rolling", days: 30 },
        unit: "count",
        precision: 0,
        is_kpi: false,
        status: "draft",
        version: 1,
    },
];

export function listDefaultEnrollmentMetricKeys(): string[] {
    return DEFAULT_ENROLLMENT_METRIC_TEMPLATES.map((m) => m.key);
}
