/**
 * COMMERCIAL FINALIZATION, AGAINST A REAL DATABASE — the November model and what survives it.
 *
 * This is deliberately NOT mocked. Everything finalization claims is a claim about the interaction
 * of four writers, two triggers and a handful of CHECK constraints, and a fake client agrees with
 * whatever the code hands it. The specific failure this suite exists to catch is the one a mock
 * cannot: a draft created while a period was open, posting into it weeks after the period was
 * finalized, because posting is an UPDATE that re-resolves nothing.
 *
 * The economics are generated by the real services from a real synthetic household, then measured
 * by re-reading the database — never by trusting a return value.
 *
 * ── THE PERIOD IS CLOSED THROUGH THE SERVICE'S DATE SEAM, NOT BY A FAKE CLOCK ──
 *
 * `closeBillingPeriod` takes `todayYmd` for exactly this. It is not a way to close early: the value
 * is compared against the period's own frozen `ends_on` precisely as a real clock would be, so a
 * date before the boundary refuses here just as it would in production. The REAL-clock proof is a
 * separate, additional obligation and does not belong in a deterministic suite.
 */
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import {
    createChildcareDraftCharge,
    postChildcareCharge,
} from "@/lib/financials/childcareChargeService";
import {
    applyPaymentToCharge,
    readChargeBalance,
    recordChildcarePayment,
} from "@/lib/financials/childcarePaymentService";
import { applyManualReduction } from "@/lib/financials/reductions/manualReductionService";
import { closeBillingPeriod } from "@/lib/financials/billingPeriods/closeBillingPeriod";
import { resolveChargeBillingPeriodBinding } from "@/lib/financials/billingPeriods/bindChargeBillingPeriod";
import { resolveFamilyCollectible } from "@/lib/financials/subsidy/resolveFamilyCollectible";

function certEnv(): { url: string; serviceKey: string } | null {
    const fromProcess = { url: process.env.CERT_SUPABASE_URL ?? "", serviceKey: process.env.CERT_SERVICE_ROLE_KEY ?? "" };
    if (fromProcess.url && fromProcess.serviceKey) return fromProcess;
    try {
        const file = readFileSync(resolve(__dirname, "../../../.env.certification.local"), "utf8");
        const read = (key: string) =>
            file.split("\n").find((l) => l.startsWith(`${key}=`))?.slice(key.length + 1).trim() ?? "";
        const url = read("SUPABASE_URL") || read("NEXT_PUBLIC_SUPABASE_URL");
        const serviceKey = read("SUPABASE_SERVICE_ROLE_KEY");
        return url && serviceKey ? { url, serviceKey } : null;
    } catch {
        return null;
    }
}

const env = certEnv();
const describeLive = env ? describe : describe.skip;

const ORG = "00000000-0000-4000-8000-000000000001";
const ACTOR = "00000000-0000-4000-8000-0000000000aa";

/*
 * RUN-UNIQUE ids. The charges this suite posts are immutable once posted, so `afterAll` cannot
 * delete them; fixed ids would make a second run read the first run's money and look like
 * duplication. (Learned the hard way on the reductionCore proof.)
 */
const RUN = randomUUID().slice(0, 8);
const P = `fd20${RUN.slice(0, 4)}-0000-4000-8000-`;
const CUSTOMER = `${P}0000000c0001`;
const MEMBER = `${P}0000000d0001`;
const PERSON = `${P}0000000e0001`;
const AGREEMENT = `${P}0000000a0001`;
const LOCATION = `${P}0000000b0001`;
const CALENDAR_POLICY = `${P}0000000f0001`;

/* A monthly household, so "November" is one period with the bounds everyone expects. */
const NOV_START = "2026-11-01";
const NOV_END = "2026-11-30";
const DEC_START = "2026-12-01";
/** The day after November ends — the first day November is eligible to close. */
const DEC_FIRST = "2026-12-01";

describeLive("commercial finalization — the November model, live", () => {
    let db: SupabaseClient;
    let novemberPeriodId: string;
    let decemberPeriodId: string;
    let tuitionChargeId: string;
    let lateChargeId: string;
    let paymentId: string;

    beforeAll(async () => {
        db = createClient(env!.url, env!.serviceKey, { auth: { persistSession: false } });

        const seed = async (table: string, row: Record<string, unknown>) => {
            const { error } = await db.from(table).upsert(row);
            expect(error, `seeding ${table}: ${error?.message ?? ""}`).toBeNull();
        };
        await seed("customers", { id: CUSTOMER, org_id: ORG, name: `Close proof ${RUN}`, customer_type: "household" });
        await seed("locations", {
            id: LOCATION, org_id: ORG, customer_id: CUSTOMER, label: `Close proof site ${RUN}`,
            location_type: "site", is_active: true,
        });
        await seed("persons", { id: PERSON, org_id: ORG, first_name: "Close", last_name: "Proof" });
        await seed("customer_members", {
            id: MEMBER, org_id: ORG, customer_id: CUSTOMER, person_id: PERSON,
            display_name: "Close Proof", relationship: "child", is_active: true,
        });
        await seed("child_enrollment_agreements", {
            id: AGREEMENT, org_id: ORG, customer_id: CUSTOMER, customer_member_id: MEMBER, person_id: PERSON,
            site_location_id: LOCATION, status: "active", start_date: "2026-01-01",
        });
        await seed("financial_policies", {
            id: CALENDAR_POLICY, org_id: ORG, scope_type: "customer", customer_id: CUSTOMER,
            location_id: null, policy_type: "billing_calendar", is_active: true,
            effective_start: "2026-01-01", effective_end: null,
            value: { cadence: "monthly", anchor_on: null },
        });

        /*
         * Materialize November and December through the REAL binder, by binding a charge-shaped
         * question at each date. Nothing is written by this; the binder materializes periods as a
         * side effect of resolving them, which is S1's job and not this suite's to reimplement.
         */
        const novBinding = await resolveChargeBillingPeriodBinding(db, {
            orgId: ORG,
            billableSourceType: "enrollment_agreement",
            billableSourceId: AGREEMENT,
            placementDate: NOV_START,
        });
        novemberPeriodId = novBinding.billing_period_id!;
        expect(novemberPeriodId, "November must materialize").toBeTruthy();

        const decBinding = await resolveChargeBillingPeriodBinding(db, {
            orgId: ORG,
            billableSourceType: "enrollment_agreement",
            billableSourceId: AGREEMENT,
            placementDate: DEC_START,
        });
        decemberPeriodId = decBinding.billing_period_id!;
        expect(decemberPeriodId).toBeTruthy();
        expect(decemberPeriodId).not.toBe(novemberPeriodId);
    });

    afterAll(async () => {
        /* Posted charges are immutable, so this cleans what it can and leaves the rest; the
         * run-unique prefix is what keeps the residue harmless. */
        await db.from("financial_reduction_applications").delete().eq("org_id", ORG).eq("customer_id", CUSTOMER);
        await db.from("charges").delete().eq("org_id", ORG).eq("billable_source_id", AGREEMENT).eq("status", "draft");
    });

    it("while November is OPEN, ordinary economics post normally: $1,000 then +$75", async () => {
        const tuition = await createChildcareDraftCharge(db, {
            orgId: ORG,
            enrollmentAgreementId: AGREEMENT,
            chargeCategory: "tuition",
            chargeType: "service",
            amountCents: 100_000,
            currencyCode: "USD",
            serviceDate: "2026-11-01",
            description: "November tuition",
            actorUserId: ACTOR,
            metadata: { source: "close_proof" },
        } as never);
        tuitionChargeId = (tuition as { id: string }).id;
        /* It bound to November canonically, which is the premise of everything below. */
        expect((tuition as { billing_period_id: string }).billing_period_id).toBe(novemberPeriodId);
        expect((tuition as { billing_period_generation: string }).billing_period_generation).toBe("canonical");
        await postChildcareCharge(db, { orgId: ORG, chargeId: tuitionChargeId, actorUserId: ACTOR });

        const late = await createChildcareDraftCharge(db, {
            orgId: ORG,
            enrollmentAgreementId: AGREEMENT,
            chargeCategory: "late_pickup",
            chargeType: "fee",
            amountCents: 7_500,
            currencyCode: "USD",
            serviceDate: "2026-11-20",
            description: "November late pickup",
            actorUserId: ACTOR,
            metadata: { source: "close_proof" },
        } as never);
        lateChargeId = (late as { id: string }).id;
        expect((late as { billing_period_id: string }).billing_period_id).toBe(novemberPeriodId);
        await postChildcareCharge(db, { orgId: ORG, chargeId: lateChargeId, actorUserId: ACTOR });

        const novemberCents = await periodEconomics(db, novemberPeriodId);
        expect(novemberCents).toBe(107_500);
    });

    it("a $1,000 payment settles the tuition, leaving $75 remaining", async () => {
        const payment = await recordChildcarePayment(db, {
            orgId: ORG,
            billableSourceType: "enrollment_agreement",
            billableSourceId: AGREEMENT,
            customerId: CUSTOMER,
            amountCents: 100_000,
            currency: "USD",
            paymentMethod: "check",
            status: "posted",
            actorUserId: ACTOR,
        } as never);
        paymentId = payment.payment.id;
        expect(paymentId).toBeTruthy();

        await applyPaymentToCharge(db, {
            orgId: ORG,
            paymentId,
            chargeId: tuitionChargeId,
            actorUserId: ACTOR,
        });

        const tuitionBalance = await readChargeBalance(db, ORG, tuitionChargeId);
        expect(tuitionBalance.outstandingCents).toBe(0);
        const lateBalance = await readChargeBalance(db, ORG, lateChargeId);
        expect(lateBalance.outstandingCents).toBe(7_500);
    });

    it("November cannot close before its boundary — no early close, even here", async () => {
        await expect(
            closeBillingPeriod(db, {
                orgId: ORG,
                billingPeriodId: novemberPeriodId,
                closeActor: "operator",
                actorUserId: ACTOR,
                todayYmd: "2026-11-12",
            }),
        ).rejects.toThrow(/has not finished yet/);
        const row = await readPeriod(db, novemberPeriodId);
        expect(row.status).toBe("open");
    });

    it("closes November after its boundary, and NOTHING about the money changes", async () => {
        const result = await closeBillingPeriod(db, {
            orgId: ORG,
            billingPeriodId: novemberPeriodId,
            closeActor: "operator",
            actorUserId: ACTOR,
            todayYmd: DEC_FIRST,
        });
        expect(result.transitioned).toBe(true);
        expect(result.closeActor).toBe("operator");
        expect(result.closedBy).toBe(ACTOR);

        const row = await readPeriod(db, novemberPeriodId);
        expect(row.status).toBe("closed");
        expect(row.closed_at).toBeTruthy();
        expect(row.close_actor).toBe("operator");
        /* The bounds are untouched — close finalizes a period, it does not restate it. */
        expect(row.starts_on).toBe(NOV_START);
        expect(row.ends_on).toBe(NOV_END);

        /* THE MODEL: $1,075 commercial, $1,000 paid, $75 remaining — after finalization. */
        expect(await periodEconomics(db, novemberPeriodId)).toBe(107_500);
        expect((await readChargeBalance(db, ORG, tuitionChargeId)).outstandingCents).toBe(0);
        expect((await readChargeBalance(db, ORG, lateChargeId)).outstandingCents).toBe(7_500);
    });

    it("OUTSTANDING DEBT SURVIVES CLOSE — the $75 is still owed and still collectible", async () => {
        const late = await readCharge(db, lateChargeId);
        expect(late.status).toBe("posted");
        expect(late.voided_at).toBeNull();
        expect(late.billing_period_id).toBe(novemberPeriodId);

        /*
         * Close is not forgiveness. Collectible truth is unchanged by finality — and the figure
         * that matters is `currentlyCollectibleCents`, the one Autopay and every collection surface
         * read. It must still be the full $75 for a period that is commercially final.
         */
        const collectible = await resolveFamilyCollectible(db, { orgId: ORG, chargeId: lateChargeId });
        expect(collectible.outstandingCents).toBe(7_500);
        expect(collectible.currentlyCollectibleCents).toBe(7_500);
    });

    it("a NEW November charge is REFUSED before anything is written", async () => {
        await expect(
            createChildcareDraftCharge(db, {
                orgId: ORG,
                enrollmentAgreementId: AGREEMENT,
                chargeCategory: "late_pickup",
                chargeType: "fee",
                amountCents: 2_500,
                currencyCode: "USD",
                serviceDate: "2026-11-25",
                description: "late November fee after close",
                actorUserId: ACTOR,
            } as never),
        ).rejects.toThrow(/This billing period is closed/);

        /* ZERO new November economics — the refusal happened before the write, not after. */
        expect(await periodEconomics(db, novemberPeriodId)).toBe(107_500);
        expect(await chargeCountForPeriod(db, novemberPeriodId)).toBe(2);
    });

    it("a NEW November reduction is REFUSED before any economic write", async () => {
        await expect(
            applyManualReduction(db, {
                orgId: ORG,
                enrollmentAgreementId: AGREEMENT,
                customerId: CUSTOMER,
                customerMemberId: MEMBER,
                chargeCategory: "credit",
                amountCents: -1_000,
                currencyCode: "USD",
                reason: "a goodwill credit against a finalized November",
                effectiveDate: "2026-11-15",
                actorUserId: ACTOR,
                idempotencyKey: `close-proof-${RUN}-nov-reduction`,
            }),
        ).rejects.toThrow(/closed/);

        /* No contra charge, no application row. The guard fired before either. */
        expect(await chargeCountForPeriod(db, novemberPeriodId)).toBe(2);
        const { data: apps } = await db
            .from("financial_reduction_applications")
            .select("id")
            .eq("org_id", ORG)
            .eq("customer_id", CUSTOMER);
        expect(apps ?? []).toHaveLength(0);
    });

    it("a November DRAFT created before close CANNOT post after it — and is preserved", async () => {
        /*
         * THE CASE A CREATION GUARD CANNOT CATCH. This draft is made while December is the open
         * period but dated into November... which the creation guard refuses. So the draft is
         * created against an OPEN period first, and the period is closed underneath it — which is
         * exactly the production sequence: bill in November, finalize November, retry the draft.
         */
        const draft = await createChildcareDraftCharge(db, {
            orgId: ORG,
            enrollmentAgreementId: AGREEMENT,
            chargeCategory: "one_time",
            chargeType: "fee",
            amountCents: 3_300,
            currencyCode: "USD",
            serviceDate: DEC_START,
            description: "a draft whose period closes under it",
            actorUserId: ACTOR,
        } as never);
        const draftId = (draft as { id: string }).id;
        expect((draft as { billing_period_id: string }).billing_period_id).toBe(decemberPeriodId);

        await closeBillingPeriod(db, {
            orgId: ORG,
            billingPeriodId: decemberPeriodId,
            closeActor: "system",
            todayYmd: "2027-01-01",
        });

        await expect(
            postChildcareCharge(db, { orgId: ORG, chargeId: draftId, actorUserId: ACTOR }),
        ).rejects.toThrow(/belongs to a billing period that is closed/);

        /* PRESERVED: still a draft, still its own period, no posting consequence. */
        const after = await readCharge(db, draftId);
        expect(after.status).toBe("draft");
        expect(after.posted_at).toBeNull();
        expect(after.voided_at).toBeNull();
        expect(after.billing_period_id).toBe(decemberPeriodId);

        /*
         * AND IT IS NOT COLLECTIBLE. `readChargeBalance` answers "amount less applied payments" for
         * any charge, draft included, so it reports 3300 here — which is the arithmetic, not a debt.
         * The question the Director asked is whether the household OWES it, and the answer is the
         * collectible position: a draft is not posted, so nothing is collectible from it.
         */
        const collectible = await resolveFamilyCollectible(db, { orgId: ORG, chargeId: draftId });
        expect(collectible.currentlyCollectibleCents).toBe(0);
        expect(collectible.outstandingCents).toBe(0);

        /* No new posted economics landed in the closed period either. */
        expect(await periodEconomics(db, decemberPeriodId)).toBe(0);
    });

    it("a PAYMENT after close settles the charge without touching the period", async () => {
        const closedBefore = await readPeriod(db, novemberPeriodId);

        const later = await recordChildcarePayment(db, {
            orgId: ORG,
            billableSourceType: "enrollment_agreement",
            billableSourceId: AGREEMENT,
            customerId: CUSTOMER,
            amountCents: 7_500,
            currency: "USD",
            paymentMethod: "check",
            status: "posted",
            actorUserId: ACTOR,
        } as never);
        const laterId = later.payment.id;

        await applyPaymentToCharge(db, {
            orgId: ORG,
            paymentId: laterId,
            chargeId: lateChargeId,
            actorUserId: ACTOR,
        });

        /* The debt settles. Settlement is not period mutation. */
        expect((await readChargeBalance(db, ORG, lateChargeId)).outstandingCents).toBe(0);

        const after = await readCharge(db, lateChargeId);
        expect(after.billing_period_id).toBe(novemberPeriodId);

        const closedAfter = await readPeriod(db, novemberPeriodId);
        expect(closedAfter.status).toBe("closed");
        expect(closedAfter.closed_at).toBe(closedBefore.closed_at);

        /* The payment itself carries no period merely because it settled a period's charge. */
        const { data: paymentRow } = await db
            .from("payments")
            .select("*")
            .eq("org_id", ORG)
            .eq("id", laterId)
            .maybeSingle();
        expect(paymentRow).toBeTruthy();
        expect(Object.keys(paymentRow as Record<string, unknown>)).not.toContain("billing_period_id");

        /* And no new commercial economics appeared inside the closed period. */
        expect(await periodEconomics(db, novemberPeriodId)).toBe(107_500);
        expect(await chargeCountForPeriod(db, novemberPeriodId)).toBe(2);
    });

    it("close is IDEMPOTENT against the real database, and the row refuses to reopen", async () => {
        const first = await readPeriod(db, novemberPeriodId);
        const again = await closeBillingPeriod(db, {
            orgId: ORG,
            billingPeriodId: novemberPeriodId,
            closeActor: "system",
            todayYmd: "2027-02-01",
        });
        expect(again.transitioned).toBe(false);
        expect(again.closedAt).toBe(first.closed_at);
        expect(again.closeActor).toBe("operator");

        const after = await readPeriod(db, novemberPeriodId);
        expect(after.closed_at).toBe(first.closed_at);
        expect(after.close_actor).toBe("operator");
        expect(after.closed_by).toBe(ACTOR);

        /* And the database itself refuses a reopen, independently of the service. */
        const { error } = await db
            .from("financial_billing_periods")
            .update({ status: "open", closed_at: null, closed_by: null, close_actor: null })
            .eq("org_id", ORG)
            .eq("id", novemberPeriodId);
        expect(error, "the database must refuse a reopen").not.toBeNull();
        expect(`${error?.message ?? ""}`).toContain("billing_period_closed");
    });

    it("ACCOUNTING IS INDEPENDENT — a closed billing period says nothing about accounting", async () => {
        /*
         * Structural, and deliberately so: the two close paths share no column, no table and no
         * service. `financial_billing_periods` has no accounting column, and the accounting period
         * table has no billing-period column, so neither close can imply the other.
         */
        const { data: billingCols } = await db
            .from("financial_billing_periods")
            .select("*")
            .eq("id", novemberPeriodId)
            .maybeSingle();
        const keys = Object.keys(billingCols as Record<string, unknown>);
        expect(keys.some((k) => k.includes("accounting"))).toBe(false);
        /* The period is commercially closed while accounting is untouched by it. */
        expect((billingCols as { status: string }).status).toBe("closed");
    });
});

/* ── readers: every assertion above measures the database, not a return value ────────────────── */

async function readPeriod(db: SupabaseClient, id: string) {
    const { data, error } = await db
        .from("financial_billing_periods")
        .select("id, status, closed_at, closed_by, close_actor, starts_on, ends_on")
        .eq("id", id)
        .maybeSingle();
    expect(error).toBeNull();
    return data as {
        id: string; status: string; closed_at: string | null; closed_by: string | null;
        close_actor: string | null; starts_on: string; ends_on: string;
    };
}

async function readCharge(db: SupabaseClient, id: string) {
    const { data, error } = await db
        .from("charges")
        .select("id, status, amount_cents, posted_at, voided_at, billing_period_id, billing_period_generation")
        .eq("id", id)
        .maybeSingle();
    expect(error).toBeNull();
    return data as {
        id: string; status: string; amount_cents: number; posted_at: string | null;
        voided_at: string | null; billing_period_id: string | null; billing_period_generation: string;
    };
}

/** The commercial economics of a period: its POSTED, non-void charges. */
async function periodEconomics(db: SupabaseClient, periodId: string): Promise<number> {
    const { data, error } = await db
        .from("charges")
        .select("amount_cents")
        .eq("org_id", ORG)
        .eq("billing_period_id", periodId)
        .eq("status", "posted")
        .is("voided_at", null);
    expect(error).toBeNull();
    return (data ?? []).reduce((sum, r) => sum + Number((r as { amount_cents: number }).amount_cents), 0);
}

async function chargeCountForPeriod(db: SupabaseClient, periodId: string): Promise<number> {
    const { data, error } = await db
        .from("charges")
        .select("id")
        .eq("org_id", ORG)
        .eq("billing_period_id", periodId);
    expect(error).toBeNull();
    return (data ?? []).length;
}
