/**
 * THE FINANCIALS WORKSPACE PROJECTION — against the real database.
 *
 * What is proven here is not arithmetic, because the projection performs none. It is SELECTION: that
 * the right work appears, that it appears at the right location, and that a site filter and a
 * site-restricted operator can each only ever see less than org scope — never more.
 *
 * The charges are generated by Thread 7 and posted by Thread 1, so the cohort is real work rather
 * than rows shaped to suit a queue.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { postChildcareCharge } from "@/lib/financials/childcareChargeService";
import { generateTuitionCharges } from "@/lib/financials/tuitionGeneration/generateTuitionCharges";
import { resolveFinancialWorkQueue } from "@/lib/financials/workspace/resolveFinancialWorkQueue";

function certEnv(): { url: string; serviceKey: string } | null {
    const fromProcess = { url: process.env.CERT_SUPABASE_URL ?? "", serviceKey: process.env.CERT_SERVICE_ROLE_KEY ?? "" };
    if (fromProcess.url && fromProcess.serviceKey) return fromProcess;
    try {
        const file = readFileSync(resolve(__dirname, "../../../.env.certification.local"), "utf8");
        const read = (k: string) => file.split("\n").find((l) => l.startsWith(`${k}=`))?.slice(k.length + 1).trim() ?? "";
        const url = read("SUPABASE_URL") || read("NEXT_PUBLIC_SUPABASE_URL");
        const serviceKey = read("SUPABASE_SERVICE_ROLE_KEY");
        return url && serviceKey ? { url, serviceKey } : null;
    } catch {
        return null;
    }
}

const env = certEnv();
const describeLive = env ? describe : describe.skip;

import { runPeriodKey } from "./certificationPeriod";

/** This run's own unbilled periods — see `certificationPeriod` for why fixed ones cannot work. */
const RUN_PERIOD = runPeriodKey();

const ORG = "00000000-0000-4000-8000-000000000001";
const OTHER_ORG = "00000000-0000-4000-8000-0000000000ff";
const ACTOR = "00000000-0000-4000-8000-0000000000aa";
const W = "6f000000-0000-4000-8000-";
const GROSS = 100_000;

describeLive("financials workspace queue — live", () => {
    const supabase = (env
        ? createClient(env.url, env.serviceKey, { auth: { persistSession: false, autoRefreshToken: false } })
        : null) as unknown as SupabaseClient;

    /** Two children of ONE household, deliberately enrolled at DIFFERENT sites. */
    const kids: Array<{ ocmId: string; memberId: string; agreementId: string; siteId: string }> = [];
    let customerId = "";
    let siteA = "";
    let siteB = "";

    const orgScope = { orgId: ORG, siteScope: "all" as const, allowedSiteLocationIds: [] as string[] };

    async function clearMoney() {
        const { data: events } = await supabase
            .from("consumption_events").select("id").eq("org_id", ORG).like("idempotency_key", "cev:tuition:%");
        const ids = ((events ?? []) as Array<{ id: string }>).map((e) => e.id);
        if (ids.length > 0) {
            await supabase.from("resolved_obligations").delete().in("consumption_event_id", ids);
            await supabase.from("consumption_events").delete().in("id", ids);
        }
        await supabase.from("charges").delete().eq("org_id", ORG).eq("status", "draft");
    }

    async function generate(periodKey: string) {
        await generateTuitionCharges(supabase, {
            orgId: ORG, periodKey, actorUserId: ACTOR,
            opportunityCustomerMemberIds: kids.map((k) => k.ocmId), today: `${periodKey}-01`,
        });
    }

    beforeAll(async () => {
        const { data: memberRows } = await supabase
            .from("customer_members").select("id, customer_id").eq("org_id", ORG)
            .eq("customer_id", "00000000-0000-4000-8000-100000000001");
        const members = ((memberRows ?? []) as Array<{ id: string; customer_id: string }>).sort((a, b) => (a.id < b.id ? -1 : 1));
        expect(members.length).toBeGreaterThanOrEqual(2);
        customerId = members[0]!.customer_id;

        // TWO REAL SITES. The whole location contract is uninteresting with one.
        const { data: siteRows } = await supabase
            .from("locations").select("id").eq("org_id", ORG).eq("location_type", "site").limit(2);
        const sites = ((siteRows ?? []) as Array<{ id: string }>).map((s) => s.id);
        expect(sites.length, "two sites are needed to prove location scope").toBeGreaterThanOrEqual(2);
        [siteA, siteB] = sites as [string, string];

        const { data: rate } = await supabase.from("commercial_tuition_rates").select("id").eq("org_id", ORG).limit(1).maybeSingle();
        const rateId = (rate as { id: string }).id;
        const { data: firstOcmRows } = await supabase
            .from("opportunity_customer_members").select("id, opportunity_id, location_id, schedule_type, program_category_id")
            .eq("org_id", ORG).eq("customer_member_id", members[0]!.id).limit(1);
        const firstOcm = (firstOcmRows ?? [])[0] as Record<string, string>;

        await clearMoney();
        await supabase.from("enrollment_pricing_terms").delete().eq("org_id", ORG);

        for (const [index, member] of members.slice(0, 2).entries()) {
            const { data: ocmRows } = await supabase
                .from("opportunity_customer_members").select("id").eq("org_id", ORG).eq("customer_member_id", member.id).limit(1);
            let ocmId = ((ocmRows ?? [])[0] as { id: string } | undefined)?.id;
            if (!ocmId) {
                ocmId = `${W}00000000e00${index + 1}`;
                await supabase.from("opportunity_customer_members").insert({
                    id: ocmId, org_id: ORG, opportunity_id: firstOcm.opportunity_id, customer_member_id: member.id,
                    schedule_type: firstOcm.schedule_type ?? "full_time", location_id: firstOcm.location_id,
                    program_category_id: firstOcm.program_category_id, metadata: { seed: "cert_workspace" },
                });
            }
            const agreementId = `${W}00000000a00${index + 1}`;
            const siteId = index === 0 ? siteA : siteB;
            /*
             * Clear an incumbent agreement that a LIVE CERTIFICATION SUITE created, and nothing else.
             *
             * One operational agreement per child per site is a real constraint, and these suites
             * work on whichever customer members the tenant happens to have, so they contend for the
             * same children. Deleting only this suite's own ids left them blocking each other;
             * deleting whatever the child held reached the mounted certification's OWN subject and
             * left it with no enrolment at all, after which every seeded charge billed the household
             * directly and the provider collection refused it — correctly.
             *
             * Provenance is the discriminator. Suites stamp `source_key` on what they create and
             * clear only that, so a fixture belonging to anything else is never in range.
             */
            await supabase.from("enrollment_pricing_terms").delete()
                .eq("org_id", ORG).eq("customer_member_id", member.id);
            await supabase.from("child_enrollment_agreements").delete()
                .eq("org_id", ORG).eq("customer_member_id", member.id)
                .eq("source_key", "live-certification");
            await supabase.from("child_enrollment_agreements").insert({
                id: agreementId, org_id: ORG, customer_member_id: member.id, customer_id: customerId,
                site_location_id: siteId, opportunity_customer_member_id: ocmId, status: "active", start_date: "2026-01-01", source_key: "live-certification",
            });
            await supabase.from("enrollment_pricing_terms").insert({
                id: `${W}00000000b00${index + 1}`, org_id: ORG, opportunity_customer_member_id: ocmId,
                customer_member_id: member.id, enrollment_agreement_id: agreementId, term_kind: "tuition",
                source_entity: "commercial_tuition_rates", source_id: rateId, recommended_source_id: rateId,
                cadence_key: "monthly", payer_type: "private_pay", amount_cents: GROSS, currency_code: "USD",
                state: "accepted", resolution_key: `workspace-${index}`, effective_start: "2026-01-01", accepted_by: ACTOR,
            });
            kids.push({ ocmId: ocmId as string, memberId: member.id, agreementId, siteId });
        }
    }, 180_000);

    afterAll(async () => {
        if (process.env.CERT_KEEP === "1") return;
        await clearMoney();
        await supabase.from("enrollment_pricing_terms").delete().eq("org_id", ORG);
        for (const kid of kids) await supabase.from("child_enrollment_agreements").delete().eq("id", kid.agreementId);
        await supabase.from("opportunity_customer_members").delete().eq("org_id", ORG).contains("metadata", { seed: "cert_workspace" });
    });

    // ── 1 · THE COHORT IS REAL DRAFT WORK, LOCATED BY PROVENANCE ────────────────────────────

    it("lists draft charges at the site their own enrolment names", async () => {
        await clearMoney();
        await generate(RUN_PERIOD);
        const queue = await resolveFinancialWorkQueue(supabase, orgScope);

        const rows = queue.rows.filter((r) => r.periodKey === RUN_PERIOD);
        expect(rows).toHaveLength(2);
        expect(queue.counts.actionable).toBe(queue.rows.length);
        for (const kid of kids) {
            const row = rows.find((r) => r.enrollmentAgreementId === kid.agreementId)!;
            expect(row, `a row for ${kid.agreementId}`).toBeTruthy();
            expect(row.locationScope).toBe("site");
            expect(row.siteLocationId, "located by its OWN agreement, not the household").toBe(kid.siteId);
            expect(row.customerId).toBe(customerId);
            // The amount is the charge's own, not a computed balance.
            expect(row.amountCents).toBe(GROSS);
        }
    }, 240_000);

    it("divides a multi-site household so one child's work never appears under the other's site", async () => {
        const atA = await resolveFinancialWorkQueue(supabase, { ...orgScope, activeSiteLocationId: siteA });
        const atB = await resolveFinancialWorkQueue(supabase, { ...orgScope, activeSiteLocationId: siteB });

        expect(atA.rows.every((r) => r.siteLocationId === siteA)).toBe(true);
        expect(atB.rows.every((r) => r.siteLocationId === siteB)).toBe(true);
        expect(atA.rows.some((r) => r.enrollmentAgreementId === kids[0]!.agreementId)).toBe(true);
        expect(atA.rows.some((r) => r.enrollmentAgreementId === kids[1]!.agreementId), "the sibling's work stays at their own site").toBe(false);
        // And the counts obey the same scope the rows do.
        expect(atA.counts.actionable).toBe(atA.rows.length);
    }, 180_000);

    // ── 2 · A SITE-RESTRICTED OPERATOR CANNOT REACH PAST THEIR SITES ────────────────────────

    it("refuses a restricted operator another site's work, with or without a filter", async () => {
        const restricted = { orgId: ORG, siteScope: "restricted" as const, allowedSiteLocationIds: [siteA] };
        const unfiltered = await resolveFinancialWorkQueue(supabase, restricted);
        expect(unfiltered.rows.every((r) => r.siteLocationId === siteA)).toBe(true);

        // Asking for a site they do not hold returns nothing — the filter narrows, never widens.
        const forged = await resolveFinancialWorkQueue(supabase, { ...restricted, activeSiteLocationId: siteB });
        expect(forged.rows).toHaveLength(0);
        expect(forged.counts.actionable).toBe(0);
    }, 180_000);

    // ── 3 · WORK WITH NO SITE PROVENANCE FOLLOWS THE CHOSEN RULE ───────────────────────────

    it("treats a household charge as org-scoped: visible at org scope, never inside a site", async () => {
        const { data: created, error } = await supabase
            .from("charges")
            .insert({
                org_id: ORG, job_id: null, billable_source_type: "customer", billable_source_id: customerId,
                charge_type: "fee", charge_category: "fee", status: "draft", currency_code: "USD",
                amount_cents: 15_000, service_date: "2033-01-05", occurs_on: "2033-01-05", billable_on: "2033-01-05",
                description: "registration", metadata: {},
            })
            .select("id").single();
        expect(error, error?.message).toBeNull();
        const householdChargeId = (created as { id: string }).id;

        const orgWide = await resolveFinancialWorkQueue(supabase, orgScope);
        const row = orgWide.rows.find((r) => r.chargeId === householdChargeId)!;
        expect(row, "a household fee is real work and appears at org scope").toBeTruthy();
        expect(row.locationScope).toBe("org");
        expect(row.siteLocationId).toBeNull();
        expect(row.locationProvenance).toBe("household_account");

        // It is NOT shown under a site heading, because it belongs to no site.
        const atA = await resolveFinancialWorkQueue(supabase, { ...orgScope, activeSiteLocationId: siteA });
        expect(atA.rows.some((r) => r.chargeId === householdChargeId)).toBe(false);

        // And a site-restricted operator does not see it either — it is inside none of their sites.
        const restricted = await resolveFinancialWorkQueue(supabase, {
            orgId: ORG, siteScope: "restricted", allowedSiteLocationIds: [siteA],
        });
        expect(restricted.rows.some((r) => r.chargeId === householdChargeId)).toBe(false);

        await supabase.from("charges").delete().eq("id", householdChargeId);
    }, 240_000);

    // ── 4 · THE COHORT IS DRAFT, AND POSTING LEAVES IT ─────────────────────────────────────

    it("drops a charge from the cohort once it is posted, and changes no money doing so", async () => {
        const before = await resolveFinancialWorkQueue(supabase, orgScope);
        const target = before.rows.find((r) => r.enrollmentAgreementId === kids[0]!.agreementId)!;
        expect(target).toBeTruthy();

        await postChildcareCharge(supabase, { orgId: ORG, chargeId: target.chargeId, actorUserId: ACTOR } as never);

        const after = await resolveFinancialWorkQueue(supabase, orgScope);
        expect(after.rows.some((r) => r.chargeId === target.chargeId), "posted work leaves the draft cohort").toBe(false);
        expect(after.counts.actionable).toBe(before.counts.actionable - 1);

        // THE PROJECTION MOVED NO MONEY. The charge is what it always was, now posted.
        const { data: charge } = await supabase
            .from("charges").select("amount_cents, status").eq("id", target.chargeId).maybeSingle();
        expect((charge as { amount_cents: number }).amount_cents).toBe(GROSS);
        expect((charge as { status: string }).status).toBe("posted");
    }, 240_000);

    // ── 5 · ORG ISOLATION ──────────────────────────────────────────────────────────────────

    it("returns nothing for another organisation", async () => {
        const other = await resolveFinancialWorkQueue(supabase, {
            orgId: OTHER_ORG, siteScope: "all", allowedSiteLocationIds: [],
        });
        expect(other.rows).toHaveLength(0);
        expect(other.counts.actionable).toBe(0);
    }, 120_000);

    // ── 6 · THE JOB VERTICAL IS NOT CHILDCARE FINANCIAL WORK ───────────────────────────────

    it("excludes job-vertical charges entirely", async () => {
        const queue = await resolveFinancialWorkQueue(supabase, orgScope);
        expect(queue.rows.every((r) => r.enrollmentAgreementId !== null || r.locationScope === "org")).toBe(true);
        const { data: jobDrafts } = await supabase
            .from("charges").select("id").eq("org_id", ORG).eq("status", "draft").eq("billable_source_type", "job");
        for (const row of (jobDrafts ?? []) as Array<{ id: string }>) {
            expect(queue.rows.some((r) => r.chargeId === row.id), "a job charge is not childcare financial work").toBe(false);
        }
    }, 120_000);
});
