/**
 * SUBSIDY — authorization, claim, remittance, variance — against the real database.
 *
 * The obligation being funded is generated by Thread 7, reduced by Thread 10 where relevant, divided
 * by Thread 6 and posted by Thread 1, so what is certified is the real chain into Thread 9.
 *
 * Two assertions recur, because they are the two ways this could go wrong in a way that hurts a real
 * family: THREAD 8'S OUTSTANDING NEVER MOVES except through a payment, and A SHORTFALL NEVER
 * SILENTLY BECOMES A FAMILY BILL. The $900/$825 case exists specifically to hold the second.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { configureResponsibilityArrangement } from "@/lib/financials/responsibility/arrangementService";
import { configureExpectedFunding } from "@/lib/financials/responsibility/expectedFundingService";
import { resolveChargeResponsibility } from "@/lib/financials/responsibility/responsibilityService";
import { resolveFamilyCollectible } from "@/lib/financials/subsidy/resolveFamilyCollectible";
import {
    reconcileRemittance, recordRemittanceAdvice, resolveSubsidyVariance, settleRemittanceWithPayment,
} from "@/lib/financials/subsidy/remittanceService";
import {
    buildSubsidyClaim, recordSubsidyAuthorization, submitSubsidyClaim, upsertFundingAgency, upsertSubsidyProgram,
} from "@/lib/financials/subsidy/subsidyService";
import { generateTuitionCharges } from "@/lib/financials/tuitionGeneration/generateTuitionCharges";
import { postChildcareCharge } from "@/lib/financials/childcareChargeService";
import { applyPaymentToCharge, recordChildcarePayment } from "@/lib/financials/childcarePaymentService";

function certEnv(): { url: string; serviceKey: string } | null {
    const fromProcess = { url: process.env.CERT_SUPABASE_URL ?? "", serviceKey: process.env.CERT_SERVICE_ROLE_KEY ?? "" };
    if (fromProcess.url && fromProcess.serviceKey) return fromProcess;
    try {
        const file = readFileSync(resolve(__dirname, "../../../.env.certification.local"), "utf8");
        const read = (k: string) => file.split("\n").find((l) => l.startsWith(`${k}=`))?.slice(k.length + 1).trim() ?? "";
        const url = read("SUPABASE_URL") || read("NEXT_PUBLIC_SUPABASE_URL");
        const serviceKey = read("SUPABASE_SERVICE_ROLE_KEY");
        return url && serviceKey ? { url, serviceKey } : null;
    } catch {
        return null;
    }
}

const env = certEnv();
const describeLive = env ? describe : describe.skip;

import { runPeriodKey } from "./certificationPeriod";

/** This run's own unbilled periods — see `certificationPeriod` for why fixed ones cannot work. */
const ORG = "00000000-0000-4000-8000-000000000001";
const OTHER_ORG = "00000000-0000-4000-8000-0000000000ff";
const ACTOR = "00000000-0000-4000-8000-0000000000aa";
const S = "6d000000-0000-4000-8000-";
const GROSS = 100_000;
const EXPECTED = 90_000;

describeLive("subsidy — authorization, claim, remittance, variance, live", () => {
    const supabase = (env
        ? createClient(env.url, env.serviceKey, { auth: { persistSession: false, autoRefreshToken: false } })
        : null) as unknown as SupabaseClient;

    const kids: Array<{ ocmId: string; memberId: string; agreementId: string }> = [];
    let customerId = "";
    let parentId = "";
    let agencyId = "";
    let programId = "";

    async function clearSubsidy() {
        for (const table of [
            "financial_subsidy_variances",
            "financial_subsidy_remittance_lines",
            "financial_subsidy_remittances",
            "financial_subsidy_claim_lines",
            "financial_subsidy_claims",
        ]) {
            const { error } = await supabase.from(table).delete().eq("org_id", ORG);
            expect(error, `${table}: ${error?.message}`).toBeNull();
        }
        await supabase.from("financial_expected_funding").delete().eq("org_id", ORG);
        await supabase.from("financial_subsidy_authorizations").delete().eq("org_id", ORG);
    }

    async function clearResponsibility() {
        await supabase.from("payment_responsibility_attributions").delete().eq("org_id", ORG);
        await supabase.from("financial_responsibility_allocations").delete().eq("org_id", ORG);
        await supabase.from("financial_responsibility_shares").delete().eq("org_id", ORG);
        await supabase.from("financial_responsibility_arrangements").delete().eq("org_id", ORG);
    }

    /** A posted, wholly-assigned obligation with expected subsidy attached — the Thread 9 input. */
    async function fundedObligation(periodKey: string, expectedCents = EXPECTED, kidIndex = 0) {
        await generateTuitionCharges(supabase, {
            orgId: ORG, periodKey, actorUserId: ACTOR,
            opportunityCustomerMemberIds: [kids[kidIndex]!.ocmId], today: `${periodKey}-01`,
        });
        const { data: chargeRows } = await supabase
            .from("charges").select("id, amount_cents, status")
            .eq("org_id", ORG).eq("charge_category", "tuition").eq("service_date", `${periodKey}-01`)
            .eq("billable_source_id", kids[kidIndex]!.agreementId);
        const charge = ((chargeRows ?? [])[0] as { id: string; status: string });
        expect(charge, `a charge must exist for ${periodKey}`).toBeTruthy();

        await resolveChargeResponsibility(supabase, { orgId: ORG, chargeId: charge.id, actorUserId: ACTOR });
        const { data: allocationRows } = await supabase
            .from("financial_responsibility_allocations").select("id, share_id, is_unassigned")
            .eq("org_id", ORG).eq("charge_id", charge.id).eq("state", "active");
        const allocation = ((allocationRows ?? []) as Array<{ id: string; share_id: string | null; is_unassigned: boolean }>)
            .find((a) => !a.is_unassigned)!;
        expect(allocation, "a named party must be responsible before subsidy can fund their share").toBeTruthy();

        const authorization = await recordSubsidyAuthorization(supabase, {
            orgId: ORG, programId, customerId, customerMemberId: kids[kidIndex]!.memberId,
            coverageStart: "2026-01-01", authorizedAmountCents: expectedCents,
            familyCopayCents: GROSS - expectedCents, actorUserId: ACTOR,
        });
        await configureExpectedFunding(supabase, {
            orgId: ORG, shareId: allocation.share_id, allocationId: allocation.id,
            fundingSourceType: "government_subsidy", fundingSourceLabel: "State Child Care Assistance",
            basis: "fixed_amount", expectedAmountCents: expectedCents,
            idempotencyKey: `fef:subsidy:${allocation.id}`, actorUserId: ACTOR,
        });
        await supabase.from("financial_expected_funding")
            .update({ subsidy_authorization_id: authorization.authorizationId })
            .eq("org_id", ORG).eq("allocation_id", allocation.id);

        if (charge.status !== "posted") {
            await postChildcareCharge(supabase, { orgId: ORG, chargeId: charge.id, actorUserId: ACTOR } as never);
        }
        return { chargeId: charge.id, allocationId: allocation.id, authorizationId: authorization.authorizationId };
    }

    async function claimAndSubmit(authorizationId: string, periodKey: string) {
        const claim = await buildSubsidyClaim(supabase, { orgId: ORG, authorizationId, periodKey, actorUserId: ACTOR });
        await submitSubsidyClaim(supabase, { orgId: ORG, claimId: claim.claimId, actorUserId: ACTOR });
        const { data: lines } = await supabase
            .from("financial_subsidy_claim_lines").select("id, claimed_amount_cents").eq("org_id", ORG).eq("claim_id", claim.claimId);
        return { claim, lines: (lines ?? []) as Array<{ id: string; claimed_amount_cents: number }> };
    }

    /** Agency money, through Thread 8, with the agency recorded as the payer. */
    async function agencyPayment(amountCents: number, chargeId: string, key: string) {
        const payment = await recordChildcarePayment(supabase, {
            orgId: ORG, billableSourceType: "enrollment_agreement", billableSourceId: kids[0]!.agreementId,
            customerId, amountCents, paymentMethod: "ach", status: "posted",
            payerEntityType: "agency", payerEntityId: agencyId,
            /*
             * The key belongs to this RUN, not to the file. A fixed key is idempotent by design, so
             * a second run got back the previous run's payment — already fully applied — and the
             * next apply failed with "only 0 cents remain unapplied". Thread 8 was right both times;
             * the certification was asking it to spend the same money twice.
             */
            idempotencyKey: `${runPeriodKey()}:${key}`, actorUserId: ACTOR,
        } as never);
        const applied = await applyPaymentToCharge(supabase, {
            orgId: ORG, paymentId: payment.payment.id, chargeId, amountCents, actorUserId: ACTOR,
        } as never);
        return { paymentId: payment.payment.id, applicationId: (applied as { allocation: { id: string } }).allocation.id };
    }

    beforeAll(async () => {
        const { data: memberRows } = await supabase
            .from("customer_members").select("id, customer_id").eq("org_id", ORG)
            .eq("customer_id", "00000000-0000-4000-8000-100000000001");
        const members = ((memberRows ?? []) as Array<{ id: string; customer_id: string }>).sort((a, b) => (a.id < b.id ? -1 : 1));
        expect(members.length).toBeGreaterThanOrEqual(2);
        customerId = members[0]!.customer_id;
        const { data: personLinks } = await supabase
            .from("customer_persons").select("person_id").eq("org_id", ORG).eq("customer_id", customerId).limit(2);
        parentId = ((personLinks ?? [])[0] as { person_id: string }).person_id;

        const { data: siteRows } = await supabase.from("locations").select("id").eq("org_id", ORG).limit(1);
        const siteLocationId = ((siteRows ?? [])[0] as { id: string }).id;
        const { data: rate } = await supabase.from("commercial_tuition_rates").select("id").eq("org_id", ORG).limit(1).maybeSingle();
        const rateId = (rate as { id: string }).id;
        const { data: firstOcmRows } = await supabase
            .from("opportunity_customer_members").select("id, opportunity_id, location_id, schedule_type, program_category_id")
            .eq("org_id", ORG).eq("customer_member_id", members[0]!.id).limit(1);
        const firstOcm = (firstOcmRows ?? [])[0] as Record<string, string>;

        await clearSubsidy();
        await clearResponsibility();
        await supabase.from("enrollment_pricing_terms").delete().eq("org_id", ORG);

        for (const [index, member] of members.slice(0, 2).entries()) {
            const { data: ocmRows } = await supabase
                .from("opportunity_customer_members").select("id").eq("org_id", ORG).eq("customer_member_id", member.id).limit(1);
            let ocmId = ((ocmRows ?? [])[0] as { id: string } | undefined)?.id;
            if (!ocmId) {
                ocmId = `${S}00000000e00${index + 1}`;
                await supabase.from("opportunity_customer_members").insert({
                    id: ocmId, org_id: ORG, opportunity_id: firstOcm.opportunity_id, customer_member_id: member.id,
                    schedule_type: firstOcm.schedule_type ?? "full_time", location_id: firstOcm.location_id,
                    program_category_id: firstOcm.program_category_id, metadata: { seed: "cert_subsidy" },
                });
            }
            const agreementId = `${S}00000000a00${index + 1}`;
            /*
             * Clear an incumbent agreement that a LIVE CERTIFICATION SUITE created, and nothing else.
             *
             * One operational agreement per child per site is a real constraint, and these suites
             * work on whichever customer members the tenant happens to have, so they contend for the
             * same children. Deleting only this suite's own ids left them blocking each other;
             * deleting whatever the child held reached the mounted certification's OWN subject and
             * left it with no enrolment at all, after which every seeded charge billed the household
             * directly and the provider collection refused it — correctly.
             *
             * Provenance is the discriminator. Suites stamp `source_key` on what they create and
             * clear only that, so a fixture belonging to anything else is never in range.
             */
            await supabase.from("enrollment_pricing_terms").delete()
                .eq("org_id", ORG).eq("customer_member_id", member.id);
            await supabase.from("child_enrollment_agreements").delete()
                .eq("org_id", ORG).eq("customer_member_id", member.id)
                .eq("source_key", "live-certification");
            await supabase.from("child_enrollment_agreements").insert({
                id: agreementId, org_id: ORG, customer_member_id: member.id, customer_id: customerId,
                site_location_id: siteLocationId, opportunity_customer_member_id: ocmId, status: "active", start_date: "2026-01-01", source_key: "live-certification",
            });
            await supabase.from("enrollment_pricing_terms").insert({
                id: `${S}00000000b00${index + 1}`, org_id: ORG, opportunity_customer_member_id: ocmId,
                customer_member_id: member.id, enrollment_agreement_id: agreementId, term_kind: "tuition",
                source_entity: "commercial_tuition_rates", source_id: rateId, recommended_source_id: rateId,
                cadence_key: "monthly", payer_type: "private_pay", amount_cents: GROSS, currency_code: "USD",
                state: "accepted", resolution_key: `subsidy-${index}`, effective_start: "2026-01-01", accepted_by: ACTOR,
            });
            kids.push({ ocmId: ocmId as string, memberId: member.id, agreementId });
        }

        // One named party carries the whole net, so every figure below is unambiguous.
        await configureResponsibilityArrangement(supabase, {
            orgId: ORG, customerId, effectiveStart: "2026-01-01", actorUserId: ACTOR,
            shares: [{ responsiblePartyId: parentId, method: "percentage", percentBasisPoints: 10_000, priority: 1 }],
        } as never);

        agencyId = (await upsertFundingAgency(supabase, {
            orgId: ORG, agencyKey: "cert-agency", name: "State Child Care Assistance", actorUserId: ACTOR,
        })).agencyId;
        programId = (await upsertSubsidyProgram(supabase, {
            orgId: ORG, agencyId, programKey: "cert-erdc", name: "Employment Related Day Care", actorUserId: ACTOR,
        })).programId;
    }, 180_000);

    afterAll(async () => {
        if (process.env.CERT_KEEP === "1") return;
        await clearSubsidy();
        await clearResponsibility();
        await supabase.from("financial_accounting_periods").delete().eq("org_id", ORG).eq("period_key", "FY-CERT-SUBSIDY");
        await supabase.from("financial_subsidy_programs").delete().eq("org_id", ORG);
        await supabase.from("financial_funding_agencies").delete().eq("org_id", ORG);
        await supabase.from("enrollment_pricing_terms").delete().eq("org_id", ORG);
        for (const kid of kids) await supabase.from("child_enrollment_agreements").delete().eq("id", kid.agreementId);
        await supabase.from("opportunity_customer_members").delete().eq("org_id", ORG).contains("metadata", { seed: "cert_subsidy" });
    });

    // ── 1 · AUTHORIZATION: EFFECTIVE DATING AND ORG ISOLATION ───────────────────────────────

    it("supersedes an authorization forward and refuses an overlapping one", async () => {
        await clearSubsidy();
        const first = await recordSubsidyAuthorization(supabase, {
            orgId: ORG, programId, customerId, customerMemberId: kids[0]!.memberId,
            coverageStart: "2026-01-01", authorizedAmountCents: 50_000, actorUserId: ACTOR,
        });
        const second = await recordSubsidyAuthorization(supabase, {
            orgId: ORG, programId, customerId, customerMemberId: kids[0]!.memberId,
            coverageStart: "2032-01-01", authorizedAmountCents: EXPECTED, actorUserId: ACTOR,
        });
        expect(second.supersededId).toBe(first.authorizationId);
        const { data: predecessor } = await supabase
            .from("financial_subsidy_authorizations").select("coverage_end, state, superseded_by_id")
            .eq("id", first.authorizationId).maybeSingle();
        expect((predecessor as Record<string, unknown>).coverage_end, "closed, not erased").toBe("2031-12-31");
        expect((predecessor as Record<string, unknown>).state).toBe("superseded");

        // The DATABASE refuses an overlap, not a read.
        await expect(
            supabase.from("financial_subsidy_authorizations").insert({
                org_id: ORG, program_id: programId, customer_id: customerId, customer_member_id: kids[0]!.memberId,
                coverage_start: "2032-06-01", state: "active",
            }).then((r) => { if (r.error) throw new Error(r.error.message); }),
        ).rejects.toThrow(/exclusion|overlap/i);
    }, 180_000);

    it("refuses a programme from another organisation", async () => {
        await expect(
            recordSubsidyAuthorization(supabase, {
                orgId: OTHER_ORG, programId, customerId, customerMemberId: kids[0]!.memberId,
                coverageStart: "2026-01-01", actorUserId: ACTOR,
            }),
        ).rejects.toThrow(/no such subsidy programme/i);
    }, 120_000);

    // ── 2 · EXPECTED FUNDING MOVES NOTHING ──────────────────────────────────────────────────

    it("records expected subsidy without payment, without reducing outstanding, and without suppressing collection", async () => {
        await clearSubsidy();
        const { chargeId } = await fundedObligation(runPeriodKey(0));
        const position = await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId });

        expect(position.expectedSubsidyCents).toBe(EXPECTED);
        expect(position.outstandingCents, "Thread 8's outstanding is untouched").toBe(GROSS);
        expect(position.actualSubsidyReceivedCents, "no cash was invented").toBe(0);
        // THE POLICY: an authorization alone suppresses nothing.
        expect(position.submittedClaimSuppressionCents).toBe(0);
        expect(position.currentlyCollectibleCents, "the family is still asked for the whole obligation").toBe(GROSS);
        expect(position.explanation.suppressionBoundBy).toBe("none");

        /*
         * Scoped to THIS obligation. Counting every payment ever made against the agreement made the
         * claim depend on how many times the certification had run before, which is not what "no
         * cash was invented by recording an expected subsidy" means.
         */
        const { data: applied } = await supabase.from("payment_allocations").select("id")
            .eq("org_id", ORG).eq("target_entity_type", "charge").eq("target_entity_id", chargeId);
        expect((applied ?? []).length, "no cash was invented for this obligation").toBe(0);
    }, 300_000);

    it("does not suppress collection for a DRAFT claim", async () => {
        const { data: authRow } = await supabase
            .from("financial_subsidy_authorizations").select("id").eq("org_id", ORG).eq("state", "active").limit(1).maybeSingle();
        const claim = await buildSubsidyClaim(supabase, {
            orgId: ORG, authorizationId: (authRow as { id: string }).id, periodKey: runPeriodKey(0), actorUserId: ACTOR,
        });
        expect(claim.lines).toBe(1);
        const { data: chargeRow } = await supabase
            .from("charges").select("id").eq("org_id", ORG).eq("charge_category", "tuition").eq("service_date", "2032-02-01").limit(1).maybeSingle();
        const position = await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId: (chargeRow as { id: string }).id });
        expect(position.submittedClaimSuppressionCents, "a draft has not been asked for").toBe(0);
        expect(position.currentlyCollectibleCents).toBe(GROSS);
    }, 240_000);

    // ── 3 · SUBMISSION IS THE EVENT ─────────────────────────────────────────────────────────

    it("suppresses family collection for the submitted amount, and only that", async () => {
        await clearSubsidy();
        const { chargeId, authorizationId } = await fundedObligation(runPeriodKey(1));
        await claimAndSubmit(authorizationId, runPeriodKey(1));

        const position = await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId });
        expect(position.outstandingCents, "outstanding STILL has not moved").toBe(GROSS);
        expect(position.submittedClaimSuppressionCents).toBe(EXPECTED);
        expect(position.currentlyCollectibleCents, "the family is asked only for their own part").toBe(GROSS - EXPECTED);
        expect(position.explanation.suppressionBoundBy).toBe("claimed");
        expect(position.actualSubsidyReceivedCents, "and still no money has arrived").toBe(0);
    }, 300_000);

    it("is idempotent to build and to submit", async () => {
        const { data: authRow } = await supabase
            .from("financial_subsidy_authorizations").select("id").eq("org_id", ORG).eq("state", "active").limit(1).maybeSingle();
        const authorizationId = (authRow as { id: string }).id;
        const rebuilt = await buildSubsidyClaim(supabase, { orgId: ORG, authorizationId, periodKey: runPeriodKey(1), actorUserId: ACTOR });
        expect(rebuilt.idempotent, "the agency is not asked twice").toBe(true);
        const resubmitted = await submitSubsidyClaim(supabase, { orgId: ORG, claimId: rebuilt.claimId, actorUserId: ACTOR });
        expect(resubmitted.alreadySubmitted).toBe(true);
        const { data: claims } = await supabase.from("financial_subsidy_claims").select("id").eq("org_id", ORG).eq("period_key", runPeriodKey(1));
        expect((claims ?? []).length).toBe(1);
    }, 240_000);

    // ── 4 · EXACT REMITTANCE, THROUGH THREAD 8 ──────────────────────────────────────────────

    it("settles an exact remittance as real money and matches it", async () => {
        await clearSubsidy();
        const { chargeId, authorizationId } = await fundedObligation(runPeriodKey(2));
        const { lines } = await claimAndSubmit(authorizationId, runPeriodKey(2));

        const advice = await recordRemittanceAdvice(supabase, {
            orgId: ORG, agencyId, externalRemittanceId: "RA-EXACT", totalAmountCents: EXPECTED,
            lines: [{ claimLineId: lines[0]!.id, amountCents: EXPECTED }],
            idempotencyKey: "fsr:cert-exact", actorUserId: ACTOR,
        });
        // ADVICE IS NOT CASH.
        let position = await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId });
        expect(position.actualSubsidyReceivedCents, "an advice is evidence, not money").toBe(0);
        expect(position.outstandingCents).toBe(GROSS);

        const { paymentId } = await agencyPayment(EXPECTED, chargeId, "pay:cert-exact");
        await settleRemittanceWithPayment(supabase, { orgId: ORG, remittanceId: advice.remittanceId, paymentId, actorUserId: ACTOR });
        const reconciled = await reconcileRemittance(supabase, { orgId: ORG, remittanceId: advice.remittanceId, actorUserId: ACTOR });
        expect(reconciled.shortPaidCents).toBe(0);

        position = await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId });
        expect(position.actualSubsidyReceivedCents, "money arrived, told apart by who paid it").toBe(EXPECTED);
        expect(position.outstandingCents, "and Thread 8 moved outstanding, as it should").toBe(GROSS - EXPECTED);
        expect(position.unresolvedVarianceCents).toBe(0);
        // The claim is settled, so it suppresses nothing further: what is left is the family's copay.
        expect(position.submittedClaimSuppressionCents).toBe(0);
        expect(position.currentlyCollectibleCents).toBe(GROSS - EXPECTED);
    }, 420_000);

    it("refuses to settle a remittance with a family's own payment", async () => {
        const { data: remittance } = await supabase
            .from("financial_subsidy_remittances").select("id").eq("org_id", ORG).limit(1).maybeSingle();
        const family = await recordChildcarePayment(supabase, {
            orgId: ORG, billableSourceType: "enrollment_agreement", billableSourceId: kids[0]!.agreementId,
            customerId, amountCents: 1_000, paymentMethod: "cash", status: "posted",
            payerEntityType: "person", payerEntityId: parentId,
            idempotencyKey: "pay:cert-family-not-agency", actorUserId: ACTOR,
        } as never);
        await expect(
            settleRemittanceWithPayment(supabase, {
                orgId: ORG, remittanceId: (remittance as { id: string }).id,
                paymentId: family.payment.id, actorUserId: ACTOR,
            }),
        ).rejects.toThrow(/payer is the agency/i);
    }, 240_000);

    // ── 5 · THE SHORTFALL, WHICH IS THE WHOLE POINT ─────────────────────────────────────────

    it("holds a $900-expected / $825-actual shortfall open and never bills the family for it", async () => {
        await clearSubsidy();
        const { chargeId, authorizationId } = await fundedObligation(runPeriodKey(3));
        const { lines } = await claimAndSubmit(authorizationId, runPeriodKey(3));
        const collectibleBefore = (await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId })).currentlyCollectibleCents;
        expect(collectibleBefore).toBe(GROSS - EXPECTED); // $100 of a $1,000 obligation

        const SHORT = 82_500;
        const advice = await recordRemittanceAdvice(supabase, {
            orgId: ORG, agencyId, externalRemittanceId: "RA-SHORT", totalAmountCents: SHORT,
            lines: [{ claimLineId: lines[0]!.id, amountCents: SHORT, adjustmentReason: "rate adjustment" }],
            idempotencyKey: "fsr:cert-short", actorUserId: ACTOR,
        });
        const { paymentId } = await agencyPayment(SHORT, chargeId, "pay:cert-short");
        await settleRemittanceWithPayment(supabase, { orgId: ORG, remittanceId: advice.remittanceId, paymentId, actorUserId: ACTOR });
        const reconciled = await reconcileRemittance(supabase, { orgId: ORG, remittanceId: advice.remittanceId, actorUserId: ACTOR });
        expect(reconciled.shortPaidCents, "$75 did not arrive").toBe(7_500);

        const { data: varianceRows } = await supabase
            .from("financial_subsidy_variances").select("id, state, variance_cents, resolution_kind").eq("org_id", ORG);
        const variance = ((varianceRows ?? [])[0] as Record<string, unknown>);
        expect(variance.state).toBe("short_paid");
        expect(Number(variance.variance_cents)).toBe(-7_500);
        expect(variance.resolution_kind, "and NOTHING was decided automatically").toBeNull();

        const position = await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId });
        expect(position.unresolvedVarianceCents).toBe(-7_500);
        /*
         * THE ASSERTION THIS THREAD EXISTS FOR. The agency is $75 short. The family's collectible
         * amount is what Thread 8 still says is outstanding less what was suppressed — it did NOT
         * quietly grow by $75 to cover the agency.
         */
        expect(position.outstandingCents).toBe(GROSS - SHORT);
        // $175 is outstanding; $75 of it is still expected from the agency and stays suppressed, so
        // the family is asked for their $100 copay — exactly what they were asked for before the
        // agency underpaid, and not a cent more.
        expect(position.currentlyCollectibleCents).toBe(GROSS - EXPECTED);
        expect(position.currentlyCollectibleCents, "the shortfall did not move onto the family").toBe(collectibleBefore);
        /*
         * Scoped to the family under test. This counted every adjustment and credit in the tenant,
         * so Thread 10's own fixtures made it fail — while saying nothing about whether THIS
         * shortfall was pushed onto THIS family, which is the claim.
         */
        const { data: adjustments } = await supabase
            .from("charges").select("id").eq("org_id", ORG)
            .eq("billable_source_id", kids[0]!.agreementId)
            .eq("service_date", `${runPeriodKey(3)}-01`)
            .in("charge_category", ["adjustment", "credit"]);
        expect((adjustments ?? []).length, "and no adjustment was written on the family's behalf").toBe(0);
    }, 480_000);

    it("resolves a shortfall only when an operator names how, and once", async () => {
        const { data: varianceRows } = await supabase
            .from("financial_subsidy_variances").select("id").eq("org_id", ORG).limit(1);
        const varianceId = ((varianceRows ?? [])[0] as { id: string }).id;

        const resolved = await resolveSubsidyVariance(supabase, {
            orgId: ORG, varianceId, resolution: "write_off",
            note: "Agency rate adjustment accepted", actorUserId: ACTOR,
        });
        expect(resolved.writeOffChargeId, "a write-off forgives it through Thread 10, not a copy").toBeTruthy();
        const { data: written } = await supabase
            .from("charges").select("amount_cents, charge_category").eq("id", resolved.writeOffChargeId!).maybeSingle();
        expect((written as { amount_cents: number }).amount_cents).toBe(-7_500);
        expect((written as { charge_category: string }).charge_category).toBe("adjustment");

        const again = await resolveSubsidyVariance(supabase, {
            orgId: ORG, varianceId, resolution: "resubmit", actorUserId: ACTOR,
        });
        expect(again.alreadyResolved, "one difference, one decision").toBe(true);
        /*
         * This run's service month, not every adjustment the tenant has ever carried. The claim is
         * that resolving a shortfall writes ONE adjustment — a count over the whole org measured how
         * many times the certification had run, not whether the resolution is idempotent.
         */
        const { data: adjustments } = await supabase
            .from("charges").select("id").eq("org_id", ORG)
            .eq("service_date", `${runPeriodKey(3)}-01`)
            .eq("charge_category", "adjustment");
        expect((adjustments ?? []).length, "and it was written exactly once").toBe(1);
    }, 300_000);

    // ── 6 · DENIAL, OVERPAYMENT, MULTI-CHILD, RECOUPMENT ────────────────────────────────────

    it("records a denial without inventing a payment", async () => {
        await clearSubsidy();
        const { chargeId, authorizationId } = await fundedObligation(runPeriodKey(4));
        const { lines } = await claimAndSubmit(authorizationId, runPeriodKey(4));
        const advice = await recordRemittanceAdvice(supabase, {
            orgId: ORG, agencyId, totalAmountCents: 0,
            lines: [{ claimLineId: lines[0]!.id, amountCents: 0, state: "denied", denialReason: "authorization lapsed" }],
            idempotencyKey: "fsr:cert-denied", actorUserId: ACTOR,
        });
        const reconciled = await reconcileRemittance(supabase, { orgId: ORG, remittanceId: advice.remittanceId, actorUserId: ACTOR });
        expect(reconciled.deniedCents).toBe(EXPECTED);

        const position = await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId });
        expect(position.actualSubsidyReceivedCents, "a denial is not money").toBe(0);
        expect(position.outstandingCents, "and it moved no outstanding").toBe(GROSS);
        const { data: variance } = await supabase
            .from("financial_subsidy_variances").select("state, resolution_kind").eq("org_id", ORG).limit(1).maybeSingle();
        expect((variance as { state: string }).state).toBe("denied");
        expect((variance as { resolution_kind: string | null }).resolution_kind, "still nobody's decision but an operator's").toBeNull();
    }, 360_000);

    it("records an overpayment as a variance rather than as extra credit", async () => {
        await clearSubsidy();
        const { chargeId, authorizationId } = await fundedObligation(runPeriodKey(5));
        const { lines } = await claimAndSubmit(authorizationId, runPeriodKey(5));
        const OVER = EXPECTED + 5_000;
        const advice = await recordRemittanceAdvice(supabase, {
            orgId: ORG, agencyId, totalAmountCents: OVER,
            lines: [{ claimLineId: lines[0]!.id, amountCents: OVER }],
            idempotencyKey: "fsr:cert-over", actorUserId: ACTOR,
        });
        const reconciled = await reconcileRemittance(supabase, { orgId: ORG, remittanceId: advice.remittanceId, actorUserId: ACTOR });
        expect(reconciled.overpaidCents).toBe(5_000);
        const { data: variance } = await supabase
            .from("financial_subsidy_variances").select("state, variance_cents").eq("org_id", ORG).limit(1).maybeSingle();
        expect((variance as { state: string }).state).toBe("overpaid");
        expect(Number((variance as { variance_cents: number }).variance_cents)).toBe(5_000);
        // Nothing was applied, so nothing was credited to the family by an agency's mistake.
        const position = await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId });
        expect(position.actualSubsidyReceivedCents).toBe(0);
        expect(position.outstandingCents).toBe(GROSS);
    }, 360_000);

    it("lets one remittance answer claims for two children", async () => {
        await clearSubsidy();
        const first = await fundedObligation(runPeriodKey(6), EXPECTED, 0);
        const second = await fundedObligation(runPeriodKey(6), EXPECTED, 1);
        const a = await claimAndSubmit(first.authorizationId, runPeriodKey(6));
        const b = await claimAndSubmit(second.authorizationId, runPeriodKey(6));
        expect(a.claim.claimId).not.toBe(b.claim.claimId);

        const advice = await recordRemittanceAdvice(supabase, {
            orgId: ORG, agencyId, totalAmountCents: EXPECTED * 2,
            lines: [
                { claimLineId: a.lines[0]!.id, amountCents: EXPECTED },
                { claimLineId: b.lines[0]!.id, amountCents: EXPECTED },
            ],
            idempotencyKey: "fsr:cert-multi", actorUserId: ACTOR,
        });
        const reconciled = await reconcileRemittance(supabase, { orgId: ORG, remittanceId: advice.remittanceId, actorUserId: ACTOR });
        expect(reconciled.variances, "one variance per child's line").toBe(2);
        expect(reconciled.shortPaidCents).toBe(0);
        // Each child's obligation is answered on its own line — a single total could not say which.
        const { data: lineRows } = await supabase
            .from("financial_subsidy_remittance_lines").select("claim_line_id").eq("org_id", ORG).eq("remittance_id", advice.remittanceId);
        expect(new Set(((lineRows ?? []) as Array<{ claim_line_id: string }>).map((r) => r.claim_line_id)).size).toBe(2);
    }, 480_000);

    it("recoups a payment through Thread 8, exactly once", async () => {
        await clearSubsidy();
        const { chargeId, authorizationId } = await fundedObligation(runPeriodKey(7));
        const { lines } = await claimAndSubmit(authorizationId, runPeriodKey(7));
        const advice = await recordRemittanceAdvice(supabase, {
            orgId: ORG, agencyId, totalAmountCents: EXPECTED,
            lines: [{ claimLineId: lines[0]!.id, amountCents: EXPECTED }],
            idempotencyKey: "fsr:cert-recoup", actorUserId: ACTOR,
        });
        const { paymentId, applicationId } = await agencyPayment(EXPECTED, chargeId, "pay:cert-recoup");
        await settleRemittanceWithPayment(supabase, { orgId: ORG, remittanceId: advice.remittanceId, paymentId, actorUserId: ACTOR });
        expect((await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId })).outstandingCents).toBe(GROSS - EXPECTED);

        // THE AGENCY TAKES IT BACK. Thread 8's own reversal, not a subsidy-shaped copy of one.
        const reversal = await supabase
            .from("payment_allocations")
            .update({ status: "reversed", reversed_at: new Date().toISOString(), reversal_reason: "agency recoupment" })
            .eq("org_id", ORG).eq("id", applicationId).eq("status", "active").select("id");
        expect((reversal.data ?? []).length, "reversed exactly once").toBe(1);
        const second = await supabase
            .from("payment_allocations").update({ status: "reversed" })
            .eq("org_id", ORG).eq("id", applicationId).eq("status", "active").select("id");
        expect((second.data ?? []).length, "a second reversal moves nothing").toBe(0);

        const position = await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId });
        expect(position.outstandingCents, "the obligation is owed again").toBe(GROSS);
        expect(position.actualSubsidyReceivedCents, "and the money is no longer counted as received").toBe(0);
    }, 480_000);

    // ── 7 · CONCURRENCY ─────────────────────────────────────────────────────────────────────

    it("converges under concurrent claim building and reconciliation", async () => {
        await clearSubsidy();
        const { authorizationId } = await fundedObligation(runPeriodKey(8));
        const built = await Promise.all([
            buildSubsidyClaim(supabase, { orgId: ORG, authorizationId, periodKey: runPeriodKey(8), actorUserId: ACTOR }),
            buildSubsidyClaim(supabase, { orgId: ORG, authorizationId, periodKey: runPeriodKey(8), actorUserId: ACTOR }),
            buildSubsidyClaim(supabase, { orgId: ORG, authorizationId, periodKey: runPeriodKey(8), actorUserId: ACTOR }),
        ]);
        expect(new Set(built.map((b) => b.claimId)).size, "one claim, however many callers").toBe(1);
        const { data: claims } = await supabase
            .from("financial_subsidy_claims").select("id").eq("org_id", ORG).eq("period_key", runPeriodKey(8));
        expect((claims ?? []).length).toBe(1);

        const claimId = built[0]!.claimId;
        await submitSubsidyClaim(supabase, { orgId: ORG, claimId, actorUserId: ACTOR });
        const { data: lines } = await supabase
            .from("financial_subsidy_claim_lines").select("id").eq("org_id", ORG).eq("claim_id", claimId);
        const lineId = ((lines ?? [])[0] as { id: string }).id;
        const advice = await recordRemittanceAdvice(supabase, {
            orgId: ORG, agencyId, totalAmountCents: EXPECTED,
            lines: [{ claimLineId: lineId, amountCents: EXPECTED }],
            idempotencyKey: "fsr:cert-concurrent", actorUserId: ACTOR,
        });
        await Promise.all([
            reconcileRemittance(supabase, { orgId: ORG, remittanceId: advice.remittanceId, actorUserId: ACTOR }),
            reconcileRemittance(supabase, { orgId: ORG, remittanceId: advice.remittanceId, actorUserId: ACTOR }),
            reconcileRemittance(supabase, { orgId: ORG, remittanceId: advice.remittanceId, actorUserId: ACTOR }),
        ]);
        const { data: variances } = await supabase
            .from("financial_subsidy_variances").select("id").eq("org_id", ORG);
        expect((variances ?? []).length, "one variance per line, not three").toBe(1);
    }, 480_000);

    // ── 8 · PERIOD AND JOURNAL ATTRIBUTION ──────────────────────────────────────────────────

    it("gives agency money the same accounting attribution any posted money gets", async () => {
        await clearSubsidy();
        const { chargeId, authorizationId } = await fundedObligation(runPeriodKey(9));
        const { lines } = await claimAndSubmit(authorizationId, runPeriodKey(9));
        const advice = await recordRemittanceAdvice(supabase, {
            orgId: ORG, agencyId, totalAmountCents: EXPECTED,
            lines: [{ claimLineId: lines[0]!.id, amountCents: EXPECTED }],
            idempotencyKey: "fsr:cert-journal", actorUserId: ACTOR,
        });
        /*
         * AN ACCOUNTING PERIOD HAS TO EXIST FOR ATTRIBUTION TO HAPPEN.
         *
         * Thread 5 records a journal entry only where a calendar period contains the date, and it
         * deliberately never lets that failure block the money — so without this the payment would
         * post correctly and simply not report anywhere. The period is authored into whatever
         * calendar the org already has, because one active calendar per org is a real constraint.
         */
        const { data: existingCalendar } = await supabase
            .from("financial_accounting_calendars").select("id").eq("org_id", ORG).eq("is_active", true).limit(1).maybeSingle();
        let calendarId = (existingCalendar as { id: string } | null)?.id ?? "";
        if (!calendarId) {
            const { error: calError } = await supabase.from("financial_accounting_calendars").insert({
                id: `${S}00000000f001`, org_id: ORG, calendar_key: "subsidy_445",
                name: "4/4/5 subsidy calendar", period_style: "four_four_five", is_active: true,
            });
            expect(calError, calError?.message).toBeNull();
            calendarId = `${S}00000000f001`;
        }
        /*
         * COVERING THE DAY THE MONEY ARRIVED, not the month it was for. A receipt attributes on its
         * RECEIVED date — service is 2032-11, cash is today — and the window deliberately opens in
         * the previous calendar month so the resulting key cannot have been read off a month.
         */
        const today = new Date();
        const opens = new Date(today);
        opens.setUTCDate(opens.getUTCDate() - 20);
        const closes = new Date(today);
        closes.setUTCDate(closes.getUTCDate() + 8);
        /*
         * REMOVED BEFORE IT IS RE-CREATED, never re-dated. Thread 5 freezes a period's boundaries
         * once anything has reported into it — the charge for this service month already did — and
         * upserting over it is refused, correctly. The harness has cleared the journal by now, so the
         * fixture period can go and come back rather than being moved under reported money.
         */
        /*
         * USE THE PERIOD THAT ALREADY COVERS TODAY, and only author one when none does.
         *
         * This used to delete and re-upsert its own fixture period unconditionally. A period's
         * boundaries freeze once anything has reported into it — and by now thousands of journal
         * entries have — so the re-author was refused, correctly, and the suite failed on a guard
         * that was doing its job. What this test actually needs is that SOME open period contains
         * the day the money arrived; which period that is was never the point.
         */
        const todayYmd = today.toISOString().slice(0, 10);
        const { data: covering } = await supabase
            .from("financial_accounting_periods").select("id")
            .eq("org_id", ORG).eq("status", "open")
            .lte("starts_on", todayYmd).gte("ends_on", todayYmd)
            .limit(1).maybeSingle();
        if (!covering) {
            const { error: periodError } = await supabase.from("financial_accounting_periods").upsert({
                id: `${S}00000000f002`, org_id: ORG, calendar_id: calendarId, period_key: "FY-CERT-SUBSIDY",
                label: "Subsidy certification period",
                starts_on: opens.toISOString().slice(0, 10),
                ends_on: closes.toISOString().slice(0, 10),
                status: "open",
            });
            expect(periodError, periodError?.message).toBeNull();
        }

        const { paymentId } = await agencyPayment(EXPECTED, chargeId, "pay:cert-journal");
        await settleRemittanceWithPayment(supabase, { orgId: ORG, remittanceId: advice.remittanceId, paymentId, actorUserId: ACTOR });

        const { data: journal } = await supabase
            .from("financial_journal_entries")
            .select("accounting_period_key, obligation_delta_cents, source_type, source_id")
            .eq("org_id", ORG).eq("source_id", paymentId);
        const rows = (journal ?? []) as Array<Record<string, unknown>>;
        expect(rows.length, "agency money reports into the journal like any other receipt").toBeGreaterThan(0);
        // The key is the PERIOD'S, not the month's — attribution Thread 5 owns and agency money obeys
        // exactly like any other receipt.
        expect(rows[0]!.accounting_period_key).toBe("FY-CERT-SUBSIDY");
    }, 420_000);
});
