/**
 * DISCOUNTS, CREDITS AND ADJUSTMENTS — against the real database.
 *
 * The gross these cases reduce is not fabricated: it is generated by Thread 7 from accepted pricing
 * terms, so what is certified here is the actual seam between the two threads rather than a
 * convenient fixture that resembles one.
 *
 * The thing being proven throughout is that GROSS DOES NOT MOVE. Every case that reduces a bill
 * re-reads the tuition charge afterwards and asserts its amount is untouched — because the failure
 * this thread exists to prevent is not "the discount was wrong", it is "the tuition quietly became
 * a different number and nobody can say what the family agreed to".
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { applyFinancialReductions } from "@/lib/financials/reductions/applyFinancialReductions";
import { applyManualReduction, reverseManualReduction } from "@/lib/financials/reductions/manualReductionService";
import { readAccountReductions } from "@/lib/financials/reductions/readAccountReductions";
import { configureResponsibilityArrangement } from "@/lib/financials/responsibility/arrangementService";
import { configureExpectedFunding } from "@/lib/financials/responsibility/expectedFundingService";
import { readAccountArrangement } from "@/lib/financials/responsibility/readAccountArrangement";
import { resolveFamilyCollectible } from "@/lib/financials/subsidy/resolveFamilyCollectible";
import { resolveAllocatableNet } from "@/lib/financials/responsibility/resolveAllocatableNet";
import { generateTuitionCharges } from "@/lib/financials/tuitionGeneration/generateTuitionCharges";
import { createChildcareDraftCharge, postChildcareCharge } from "@/lib/financials/childcareChargeService";
import {
    applyPaymentToCharge,
    readChargeBalance,
    readPaymentRefundedCents,
    readPaymentUnappliedCents,
    recordChildcarePayment,
    refundChildcarePayment,
} from "@/lib/financials/childcarePaymentService";
import { resolveHouseholdEligibility } from "@/lib/financials/reductions/resolveReductionEligibility";

function certEnv(): { url: string; serviceKey: string } | null {
    const fromProcess = { url: process.env.CERT_SUPABASE_URL ?? "", serviceKey: process.env.CERT_SERVICE_ROLE_KEY ?? "" };
    if (fromProcess.url && fromProcess.serviceKey) return fromProcess;
    try {
        const file = readFileSync(resolve(__dirname, "../../../.env.certification.local"), "utf8");
        const read = (key: string) =>
            file.split("\n").find((l) => l.startsWith(`${key}=`))?.slice(key.length + 1).trim() ?? "";
        const url = read("SUPABASE_URL") || read("NEXT_PUBLIC_SUPABASE_URL");
        const serviceKey = read("SUPABASE_SERVICE_ROLE_KEY");
        return url && serviceKey ? { url, serviceKey } : null;
    } catch {
        return null;
    }
}

const env = certEnv();
const describeLive = env ? describe : describe.skip;

const ORG = "00000000-0000-4000-8000-000000000001";
const OTHER_ORG = "00000000-0000-4000-8000-0000000000ff";
const ACTOR = "00000000-0000-4000-8000-0000000000aa";
const R = "7a000000-0000-4000-8000-";
const POLICY_SIBLING = `${R}00000000d001`;
const POLICY_DISCOUNT = `${R}00000000d002`;
const POLICY_WAIVER = `${R}00000000d003`;
const POLICY_SECOND = `${R}00000000d004`;

describeLive("financial reductions — discounts, credits and adjustments, live", () => {
    const supabase = (env
        ? createClient(env.url, env.serviceKey, { auth: { persistSession: false, autoRefreshToken: false } })
        : null) as unknown as SupabaseClient;

    /** The household under test: two children, both enrolled, both with accepted tuition. */
    const kids: Array<{ ocmId: string; memberId: string; agreementId: string; termId: string }> = [];
    let customerId = "";
    let siteLocationId = "";
    let rateId = "";
    let personId = "";
    const PERIOD = "2029-04";
    const PERIOD_START = "2029-04-01";
    const GROSS_CENTS = 100_000;

    // ── FIXTURE PLUMBING ─────────────────────────────────────────────────────────────────────

    async function clearReductions() {
        // Applications first: `charge_id` is ON DELETE RESTRICT, because a reduction charge must not
        // be removable out from under the decision that explains it.
        const { error: appError } = await supabase.from("financial_reduction_applications").delete().eq("org_id", ORG);
        expect(appError, appError?.message).toBeNull();
        const { error: chargeError } = await supabase
            .from("charges").delete().eq("org_id", ORG)
            .in("charge_category", ["discount", "credit", "adjustment"]).eq("status", "draft");
        expect(chargeError, chargeError?.message).toBeNull();
    }

    async function clearPolicies() {
        await supabase.from("commercial_policies").delete().eq("org_id", ORG).in("policy_type", ["discount", "sibling_discount", "waiver"]);
    }

    async function clearTuition() {
        const { data: events } = await supabase
            .from("consumption_events").select("id").eq("org_id", ORG).like("idempotency_key", "cev:tuition:%");
        const ids = ((events ?? []) as Array<{ id: string }>).map((e) => e.id);
        if (ids.length > 0) {
            await supabase.from("resolved_obligations").delete().in("consumption_event_id", ids);
            await supabase.from("consumption_events").delete().in("id", ids);
        }
        await supabase.from("charges").delete().eq("org_id", ORG).eq("charge_category", "tuition").eq("status", "draft");
        /*
         * A POSTED tuition charge left behind cannot be cleaned up here: it cannot be deleted while
         * its payment applications exist, and a posted childcare charge cannot be voided in place —
         * both are deliberate immutability, and attempting either silently changes nothing. The
         * only safe rule is therefore not to CREATE one from a case that does not need it.
         */
    }

    async function authorPolicy(id: string, policyType: string, value: Record<string, unknown>, over: Record<string, unknown> = {}) {
        const { error } = await supabase.from("commercial_policies").upsert({
            id,
            org_id: ORG,
            scope_type: "org",
            policy_type: policyType,
            label: policyType,
            value,
            effective_start: "2026-01-01",
            is_active: true,
            ...over,
        });
        expect(error, error?.message).toBeNull();
    }

    /** Real gross, produced by Thread 7 from the accepted terms — never hand-written. */
    async function generateGross(periodKey = PERIOD) {
        const result = await generateTuitionCharges(supabase, {
            orgId: ORG,
            periodKey,
            actorUserId: ACTOR,
            opportunityCustomerMemberIds: kids.map((k) => k.ocmId),
            today: `${periodKey}-01`,
        });
        return result;
    }

    async function grossCharges(periodKey = PERIOD) {
        const { data } = await supabase
            .from("charges")
            .select("id, amount_cents, status, billable_source_id, service_date")
            .eq("org_id", ORG)
            .eq("charge_category", "tuition")
            .eq("service_date", `${periodKey}-01`);
        return (data ?? []) as Array<{ id: string; amount_cents: number; status: string; billable_source_id: string; service_date: string }>;
    }

    /*
     * SCOPED TO THE PERIOD UNDER TEST. An unscoped read here made nine cases fail for one reason:
     * the posted-reduction case posted whichever row sorted first, which was a leftover from an
     * earlier case, and every later assertion counted rows that belonged to a different month.
     */
    async function reductionCharges(periodKey = PERIOD) {
        const { data } = await supabase
            .from("charges")
            .select("id, amount_cents, status, charge_category, billable_source_id, service_date, metadata")
            .eq("org_id", ORG)
            .in("charge_category", ["discount", "credit", "adjustment"])
            .eq("service_date", `${periodKey}-01`)
            .order("created_at");
        return (data ?? []) as Array<Record<string, unknown>>;
    }

    async function applications() {
        const { data } = await supabase
            .from("financial_reduction_applications")
            .select("*")
            .eq("org_id", ORG)
            .order("created_at");
        return (data ?? []) as Array<Record<string, unknown>>;
    }

    async function run(scopeToHousehold = true) {
        return applyFinancialReductions(supabase, {
            orgId: ORG,
            periodKey: PERIOD,
            actorUserId: ACTOR,
            customerIds: scopeToHousehold ? [customerId] : null,
        });
    }

    beforeAll(async () => {
        // A household that actually has two children, chosen from the tenant rather than invented.
        const { data: memberRows } = await supabase
            .from("customer_members")
            .select("id, customer_id")
            .eq("org_id", ORG)
            .eq("customer_id", "00000000-0000-4000-8000-100000000001");
        const members = ((memberRows ?? []) as Array<{ id: string; customer_id: string }>).sort((a, b) => (a.id < b.id ? -1 : 1));
        expect(members.length, "the representative tenant must have a two-child household").toBeGreaterThanOrEqual(2);
        customerId = members[0]!.customer_id;

        const { data: siteRows } = await supabase.from("locations").select("id").eq("org_id", ORG).limit(1);
        siteLocationId = ((siteRows ?? [])[0] as { id: string }).id;
        const { data: rate } = await supabase.from("commercial_tuition_rates").select("id").eq("org_id", ORG).limit(1).maybeSingle();
        rateId = (rate as { id: string }).id;

        await clearReductions();
        await clearPolicies();
        await clearTuition();
        await supabase.from("enrollment_pricing_terms").delete().eq("org_id", ORG);

        /*
         * THE REPRESENTATIVE TENANT GIVES EACH HOUSEHOLD ONE ASSIGNED CHILD.
         *
         * A sibling discount needs two, so the sibling's assignment is part of this fixture — on the
         * SAME opportunity as the first child, which is what a family enquiring about two children
         * actually looks like. Everything else is the tenant's own. The absence is worth naming:
         * nothing in the seed exercises a multi-child household, so nothing in the platform had ever
         * been run against one.
         */
        const { data: firstOcmRows } = await supabase
            .from("opportunity_customer_members")
            .select("id, opportunity_id, location_id, schedule_type, program_category_id")
            .eq("org_id", ORG)
            .eq("customer_member_id", members[0]!.id)
            .limit(1);
        const firstOcm = (firstOcmRows ?? [])[0] as
            | { id: string; opportunity_id: string; location_id: string | null; schedule_type: string | null; program_category_id: string | null }
            | undefined;
        expect(firstOcm, "the household's first child must have an assignment").toBeTruthy();

        for (const [index, member] of members.slice(0, 2).entries()) {
            const { data: ocmRows } = await supabase
                .from("opportunity_customer_members")
                .select("id")
                .eq("org_id", ORG)
                .eq("customer_member_id", member.id)
                .limit(1);
            let ocmId = ((ocmRows ?? [])[0] as { id: string } | undefined)?.id;
            if (!ocmId) {
                ocmId = `${R}00000000e00${index + 1}`;
                const { error: ocmError } = await supabase.from("opportunity_customer_members").insert({
                    id: ocmId,
                    org_id: ORG,
                    opportunity_id: firstOcm!.opportunity_id,
                    customer_member_id: member.id,
                    schedule_type: firstOcm!.schedule_type ?? "full_time",
                    location_id: firstOcm!.location_id,
                    program_category_id: firstOcm!.program_category_id,
                    metadata: { seed: "cert_reductions" },
                });
                expect(ocmError, ocmError?.message).toBeNull();
            }

            const agreementId = `${R}00000000a00${index + 1}`;
            const termId = `${R}00000000b00${index + 1}`;
            /*
             * The uniqueness this collides with is (org, member, site) — not the id. Deleting only
             * this suite's own id leaves an agreement created under ANOTHER id for the same child
             * and site in place, and the insert below then fails on a constraint the seed never
             * names. A run that died before its cleanup is enough to cause it, and the shared cert
             * tenant makes that ordinary rather than rare.
             */
            await supabase
                .from("child_enrollment_agreements")
                .delete()
                .eq("org_id", ORG)
                .eq("customer_member_id", member.id)
                .eq("site_location_id", siteLocationId);
            await supabase.from("child_enrollment_agreements").delete().eq("id", agreementId);
            const { error: agreementError } = await supabase.from("child_enrollment_agreements").insert({
                id: agreementId,
                org_id: ORG,
                customer_member_id: member.id,
                customer_id: customerId,
                site_location_id: siteLocationId,
                opportunity_customer_member_id: ocmId,
                status: "active",
                // Distinct starts, so the sibling ranking is decided by enrolment order, not by luck.
                start_date: index === 0 ? "2026-01-01" : "2026-06-01",
            });
            expect(agreementError, agreementError?.message).toBeNull();

            const { error: termError } = await supabase.from("enrollment_pricing_terms").insert({
                id: termId,
                org_id: ORG,
                opportunity_customer_member_id: ocmId,
                customer_member_id: member.id,
                enrollment_agreement_id: agreementId,
                term_kind: "tuition",
                source_entity: "commercial_tuition_rates",
                source_id: rateId,
                recommended_source_id: rateId,
                cadence_key: "monthly",
                payer_type: "private_pay",
                amount_cents: GROSS_CENTS,
                currency_code: "USD",
                state: "accepted",
                resolution_key: `reductions-${index}`,
                effective_start: "2026-01-01",
                accepted_by: ACTOR,
            });
            expect(termError, termError?.message).toBeNull();

            kids.push({ ocmId: ocmId as string, memberId: member.id, agreementId, termId });
        }

        const { data: personRows } = await supabase
            .from("customer_persons").select("person_id").eq("org_id", ORG).eq("customer_id", customerId).limit(1);
        personId = ((personRows ?? [])[0] as { person_id: string } | undefined)?.person_id ?? "";
    }, 120_000);

    afterAll(async () => {
        if (process.env.CERT_KEEP === "1") return;
        await clearReductions();
        await clearPolicies();
        await clearTuition();
        await supabase.from("employments").delete().eq("org_id", ORG).eq("source_key", "cert_reductions");
        await supabase.from("enrollment_pricing_terms").delete().eq("org_id", ORG);
        for (const kid of kids) await supabase.from("child_enrollment_agreements").delete().eq("id", kid.agreementId);
        await supabase.from("opportunity_customer_members").delete().eq("org_id", ORG).contains("metadata", { seed: "cert_reductions" });
    });

    // ── 1 · SIBLING PERCENTAGE ───────────────────────────────────────────────────────────────

    it("discounts the second child and not the first, leaving both tuitions untouched", async () => {
        await clearReductions();
        await clearTuition();
        await clearPolicies();
        await authorPolicy(POLICY_SIBLING, "sibling_discount", { basis: "percentage", value: 15, label: "Sibling discount" });

        const generated = await generateGross();
        /*
         * BOTH CHILDREN ARE BILLED FOR THE PERIOD — generated now, or already billed by a case that
         * could not clean up after itself. A posted childcare charge is immutable by design: it
         * cannot be voided in place, cannot be deleted, and its payment applications cannot be
         * deleted either, so a term billed once stays billed for the life of the fixture. What this
         * case is about is which child gets the discount, not which call created the charge, so the
         * setup asserts the OUTCOME it needs rather than the path taken to it.
         */
        expect(
            generated.counts.generated + (generated.counts.alreadyPosted ?? 0),
            JSON.stringify(generated.outcomes),
        ).toBe(2);
        const gross = await grossCharges();
        expect(gross).toHaveLength(2);

        const result = await run();
        expect(result.counts.applied, JSON.stringify(result.outcomes)).toBe(1);
        expect(result.counts.notEligible).toBe(1);

        // GROSS IS UNTOUCHED — the whole point.
        const grossAfter = await grossCharges();
        expect(grossAfter.map((c) => c.amount_cents)).toEqual([GROSS_CENTS, GROSS_CENTS]);

        const reductions = await reductionCharges();
        expect(reductions).toHaveLength(1);
        expect(reductions[0]!.amount_cents).toBe(-15_000);
        expect(reductions[0]!.charge_category).toBe("discount");

        // ATTRIBUTION: the reduction belongs to the SECOND child's enrolment, not the household's
        // first agreement and not whichever row sorted first.
        const secondKid = kids[1]!;
        expect(reductions[0]!.billable_source_id).toBe(secondKid.agreementId);

        // THE DECISION IS RECORDED, with what it was calculated on and the policy as it stood.
        const apps = await applications();
        expect(apps).toHaveLength(1);
        expect(apps[0]!.reduction_kind).toBe("policy");
        expect(apps[0]!.commercial_policy_id).toBe(POLICY_SIBLING);
        expect(apps[0]!.policy_kind).toBe("sibling_discount");
        expect(apps[0]!.basis).toBe("percentage");
        expect(Number(apps[0]!.basis_value)).toBe(15);
        expect(Number(apps[0]!.basis_amount_cents)).toBe(GROSS_CENTS);
        expect(apps[0]!.customer_member_id).toBe(secondKid.memberId);
        expect(apps[0]!.period_key).toBe(PERIOD);
        expect((apps[0]!.policy_snapshot as { params: Record<string, unknown> }).params.value).toBe(15);
    }, 180_000);

    it("retires the reduction when the sibling's enrolment no longer covers the period, while the draft is still a draft", async () => {
        /*
         * The second child's enrolment ends before the period — they are no longer concurrent.
         *
         * EVERY agreement that child holds has to end, not just this suite's own. The resolver reads
         * agreements and keeps any that covers the period, and the shared certification tenant holds
         * rows other suites created for the same member at other sites: ending one of several leaves
         * the child concurrent through a row this test never mentions, and the assertion then fails
         * for a reason that has nothing to do with the rule being tested.
         */
        const { data: heldRows } = await supabase
            .from("child_enrollment_agreements")
            .select("id, end_date")
            .eq("org_id", ORG)
            .eq("customer_member_id", kids[1]!.memberId);
        const held = (heldRows ?? []) as Array<{ id: string; end_date: string | null }>;
        for (const a of held) {
            await supabase.from("child_enrollment_agreements").update({ end_date: "2029-01-31" }).eq("id", a.id);
        }
        const facts = await resolveHouseholdEligibility(supabase, {
            orgId: ORG, customerId, periodStart: PERIOD_START, periodEnd: "2029-04-30",
        });
        expect(facts.byMember.get(kids[1]!.memberId), "an ended enrolment is not a concurrent sibling").toBeUndefined();

        // Restore each one to exactly what it was, rather than blanking them all to null.
        for (const a of held) {
            await supabase.from("child_enrollment_agreements").update({ end_date: a.end_date }).eq("id", a.id);
        }
    }, 120_000);

    // ── 2 · EMPLOYEE ELIGIBILITY, FROM THE CANONICAL EMPLOYMENT FACT ────────────────────────

    it("withholds a staff discount from a household with no employment, and grants it when one exists", async () => {
        await clearReductions();
        await clearTuition();
        await clearPolicies();
        await supabase.from("employments").delete().eq("org_id", ORG).eq("source_key", "cert_reductions");
        await authorPolicy(POLICY_DISCOUNT, "discount", {
            basis: "amount", value: 5_000, requires: "employee_household", label: "Staff discount",
        });
        await generateGross();

        const withoutEmployment = await run();
        expect(withoutEmployment.counts.applied).toBe(0);
        expect(withoutEmployment.outcomes.every((o) => o.kind === "not_eligible" && o.reason === "not_an_employee_household")).toBe(true);
        expect(await reductionCharges()).toHaveLength(0);

        expect(personId, "the household must have a person to employ").toBeTruthy();
        const { error: employmentError } = await supabase.from("employments").insert({
            org_id: ORG,
            person_id: personId,
            employment_status: "active",
            employment_type: "full_time",
            start_date: "2026-01-01",
            source_key: "cert_reductions",
        });
        expect(employmentError, employmentError?.message).toBeNull();

        const withEmployment = await run();
        // BOTH children of a staff family, at a fixed amount each — the discount is the household's.
        expect(withEmployment.counts.applied, JSON.stringify(withEmployment.outcomes)).toBe(2);
        const reductions = await reductionCharges();
        expect(reductions.map((r) => r.amount_cents)).toEqual([-5_000, -5_000]);
        expect((await grossCharges()).map((c) => c.amount_cents)).toEqual([GROSS_CENTS, GROSS_CENTS]);
    }, 180_000);

    // ── 3 · STACKING, EXCLUSIVITY, CAPS AND THE FLOOR ───────────────────────────────────────

    it("stacks a sibling percentage with a fixed discount, additively and in a fixed order", async () => {
        await clearReductions();
        await clearTuition();
        await clearPolicies();
        await authorPolicy(POLICY_SIBLING, "sibling_discount", { basis: "percentage", value: 15, label: "Sibling discount" });
        await authorPolicy(POLICY_DISCOUNT, "discount", { basis: "amount", value: 5_000, label: "Community discount" });
        await generateGross();

        const result = await run();
        expect(result.counts.applied).toBe(2);
        const apps = await applications();
        // First child: the flat discount only. Second child: sibling THEN flat, in that order.
        const second = apps.filter((a) => a.customer_member_id === kids[1]!.memberId);
        expect(second.map((a) => a.policy_kind)).toEqual(["sibling_discount", "discount"]);
        const secondCharge = (await reductionCharges()).find((c) => c.billable_source_id === kids[1]!.agreementId)!;
        expect(secondCharge.amount_cents).toBe(-20_000); // 15,000 + 5,000 — never 15,000 then 15% of the rest
    }, 180_000);

    it("lets a waiver end the question rather than stack onto zero", async () => {
        await clearReductions();
        await clearTuition();
        await clearPolicies();
        await authorPolicy(POLICY_WAIVER, "waiver", { label: "Hardship waiver" });
        await authorPolicy(POLICY_SIBLING, "sibling_discount", { basis: "percentage", value: 15, label: "Sibling discount" });
        await generateGross();

        await run();
        const apps = await applications();
        expect(apps.every((a) => a.policy_kind === "waiver")).toBe(true);
        const charges = await reductionCharges();
        expect(charges.map((c) => c.amount_cents)).toEqual([-GROSS_CENTS, -GROSS_CENTS]);
    }, 180_000);

    it("bounds a benefit at its cap and never drives the balance below zero", async () => {
        await clearReductions();
        await clearTuition();
        await clearPolicies();
        await authorPolicy(POLICY_DISCOUNT, "discount", {
            basis: "percentage", value: 90, max_benefit_cents: 10_000, label: "Capped discount",
        });
        await generateGross();

        await run();
        const apps = await applications();
        expect(apps.every((a) => a.capped === true)).toBe(true);
        expect(apps.every((a) => Number(a.amount_cents) === -10_000)).toBe(true);
        // Gross 100,000 less 10,000 — the cap bound it, not the floor.
        const charges = await reductionCharges();
        expect(charges.every((c) => c.amount_cents === -10_000)).toBe(true);
    }, 180_000);

    it("refuses rather than choosing when two policies of one kind are active", async () => {
        await clearReductions();
        await clearTuition();
        await clearPolicies();
        await authorPolicy(POLICY_DISCOUNT, "discount", { basis: "percentage", value: 10 });
        await authorPolicy(POLICY_SECOND, "discount", { basis: "percentage", value: 25 });
        await generateGross();

        const result = await run();
        expect(result.counts.refused).toBe(2);
        expect(result.counts.applied).toBe(0);
        expect(await reductionCharges()).toHaveLength(0);
        // Nothing was written, so nothing has to be undone once the configuration is fixed.
        expect(await applications()).toHaveLength(0);
    }, 180_000);

    // ── 4 · EFFECTIVE DATING ────────────────────────────────────────────────────────────────

    it("does not apply a policy that starts after the period, or one that ended before it", async () => {
        await clearReductions();
        await clearTuition();
        await clearPolicies();
        await authorPolicy(POLICY_DISCOUNT, "discount", { basis: "amount", value: 5_000 }, { effective_start: "2029-05-01" });
        await generateGross();
        expect((await run()).counts.applied, "a future policy must not discount early").toBe(0);

        await clearPolicies();
        await authorPolicy(POLICY_DISCOUNT, "discount", { basis: "amount", value: 5_000 }, { effective_start: "2026-01-01", effective_end: "2029-03-31" });
        expect((await run()).counts.applied, "an ended policy must not discount late").toBe(0);
        expect(await reductionCharges()).toHaveLength(0);
    }, 180_000);

    it("does not rewrite an application when the policy is edited afterwards", async () => {
        await clearReductions();
        await clearTuition();
        await clearPolicies();
        await authorPolicy(POLICY_DISCOUNT, "discount", { basis: "amount", value: 5_000, label: "Community discount" });
        await generateGross();
        await run();

        const before = await applications();
        expect(before.length).toBeGreaterThan(0);
        const snapshotBefore = (before[0]!.policy_snapshot as { params: { value: number } }).params.value;
        expect(snapshotBefore).toBe(5_000);

        // The tenant doubles the discount today. What was already applied stays what it was.
        await authorPolicy(POLICY_DISCOUNT, "discount", { basis: "amount", value: 10_000, label: "Community discount" });
        const after = await applications();
        expect((after[0]!.policy_snapshot as { params: { value: number } }).params.value).toBe(5_000);
        expect(Number(after[0]!.amount_cents)).toBe(-5_000);
    }, 180_000);

    // ── 5 · RETRY, CONCURRENCY AND PERIOD IDENTITY ──────────────────────────────────────────

    it("is harmless to retry, converges under concurrency, and bills a distinct period on its own", async () => {
        await clearReductions();
        await clearTuition();
        await clearPolicies();
        await authorPolicy(POLICY_DISCOUNT, "discount", { basis: "amount", value: 5_000 });
        await generateGross();

        const first = await run();
        expect(first.counts.applied).toBe(2);
        const second = await run();
        expect(second.counts.unchanged, "a sequential retry changes nothing").toBe(2);
        expect(await reductionCharges()).toHaveLength(2);

        // FOUR AT ONCE. Both callers may truthfully answer; the PERSISTED ROWS are what matter.
        await Promise.all([run(), run(), run(), run()]);
        expect(await reductionCharges(), "concurrency converges on one reduction per child").toHaveLength(2);
        expect(await applications()).toHaveLength(2);

        // A DISTINCT eligible period gets its own reduction — the identity is per gross charge.
        const nextGenerated = await generateTuitionCharges(supabase, {
            orgId: ORG, periodKey: "2029-05", actorUserId: ACTOR,
            opportunityCustomerMemberIds: kids.map((k) => k.ocmId), today: "2029-05-01",
        });
        expect(nextGenerated.counts.generated).toBe(2);
        const may = await applyFinancialReductions(supabase, { orgId: ORG, periodKey: "2029-05", actorUserId: ACTOR, customerIds: [customerId] });
        expect(may.counts.applied, "the next month is a new obligation, not a repeat").toBe(2);
        expect(await applications()).toHaveLength(4);
    }, 300_000);

    it("keeps another organisation's period out of this one's run", async () => {
        await clearReductions();
        await clearTuition();
        await clearPolicies();
        await authorPolicy(POLICY_DISCOUNT, "discount", { basis: "amount", value: 5_000 });
        await generateGross();
        const other = await applyFinancialReductions(supabase, { orgId: OTHER_ORG, periodKey: PERIOD, actorUserId: ACTOR, customerIds: null });
        expect(other.counts.applied).toBe(0);
        expect(await reductionCharges(), "this org's ledger is untouched by the other org's run").toHaveLength(0);
    }, 180_000);

    // ── 6 · POSTED IS HISTORY ───────────────────────────────────────────────────────────────

    it("reports a posted reduction and rewrites nothing when the period is re-run", async () => {
        // ITS OWN MONTH. Posted money cannot be cleared by this file — that is the guarantee the
        // thread depends on — so it is kept out of every other case's period rather than tidied up.
        const POSTED_PERIOD = "2029-07";
        await clearReductions();
        await clearTuition();
        await clearPolicies();
        await authorPolicy(POLICY_DISCOUNT, "discount", { basis: "amount", value: 5_000, label: "Community discount" });
        await generateTuitionCharges(supabase, {
            orgId: ORG, periodKey: POSTED_PERIOD, actorUserId: ACTOR,
            opportunityCustomerMemberIds: kids.map((k) => k.ocmId), today: `${POSTED_PERIOD}-01`,
        });
        const postedRun = () => applyFinancialReductions(supabase, {
            orgId: ORG, periodKey: POSTED_PERIOD, actorUserId: ACTOR, customerIds: [customerId],
        });
        const firstRun = await postedRun();
        /*
         * THE CHARGE THIS RUN PRODUCED — not whichever one the period scan sorted first. Posted
         * reduction money from an earlier execution cannot be cleared by this file (that refusal is
         * the guarantee being certified), so a scan can hand back a stranger's row, and posting it
         * proves nothing while leaving this run's drafts untouched.
         */
        const applied = firstRun.outcomes.find((o) => o.kind === "applied");
        expect(applied, JSON.stringify(firstRun.outcomes)).toBeTruthy();
        const reduction = { id: (applied as { chargeId: string }).chargeId };
        await postChildcareCharge(supabase, { orgId: ORG, chargeId: reduction.id, actorUserId: ACTOR } as never);

        // The tenant changes its mind about the amount. The posted month does not move.
        await authorPolicy(POLICY_DISCOUNT, "discount", { basis: "amount", value: 25_000, label: "Community discount" });
        const rerun = await postedRun();
        expect(rerun.counts.alreadyPosted, JSON.stringify(rerun.outcomes)).toBeGreaterThanOrEqual(1);

        const { data: after } = await supabase.from("charges").select("amount_cents, status").eq("id", reduction.id).maybeSingle();
        expect((after as { amount_cents: number; status: string }).amount_cents).toBe(-5_000);
        expect((after as { status: string }).status).toBe("posted");
    }, 240_000);

    it("attributes a posted reduction to the 4/4/5 accounting period, not to its billing month", async () => {
        /*
         * A MONTHLY BILL AND A 4/4/5 LEDGER DISAGREE ON PURPOSE. The reduction is billed in
         * 2029-08; the accounting period that contains its posting OPENS IN JULY. If attribution
         * were taken from the billing month the key could not read FY2029-P08 — which is exactly
         * why Thread 5 made them separate identities, and why a reduction must obey the same rule
         * as the tuition it reduces rather than getting a shortcut of its own.
         */
        const ATTRIBUTION_PERIOD = "2029-08";
        const CALENDAR = `${R}00000000f001`;
        await clearReductions();
        await clearPolicies();
        await authorPolicy(POLICY_DISCOUNT, "discount", { basis: "amount", value: 5_000, label: "Community discount" });

        /*
         * ONE ACTIVE CALENDAR PER ORG is a real constraint, and Thread 7's matrix already leaves one
         * standing. So this case AUTHORS ITS PERIOD INTO WHATEVER CALENDAR THE ORG HAS rather than
         * creating a second — which is also the more honest test, because a tenant has one calendar
         * and every posted consequence attributes through it.
         */
        const { data: existingCalendar } = await supabase
            .from("financial_accounting_calendars")
            .select("id").eq("org_id", ORG).eq("is_active", true).limit(1).maybeSingle();
        let calendarId = (existingCalendar as { id: string } | null)?.id ?? "";
        if (!calendarId) {
            const { error: calError } = await supabase.from("financial_accounting_calendars").insert({
                id: CALENDAR,
                org_id: ORG,
                calendar_key: "reductions_445",
                name: "4/4/5 reductions calendar",
                period_style: "four_four_five",
                is_active: true,
            });
            expect(calError, calError?.message).toBeNull();
            calendarId = CALENDAR;
        }
        const { error: perError } = await supabase.from("financial_accounting_periods").upsert({
            id: `${R}00000000f002`,
            org_id: ORG,
            calendar_id: calendarId,
            period_key: "FY2029-P08",
            label: "Period 8",
            starts_on: "2029-07-26",
            ends_on: "2029-08-22",
            status: "open",
        });
        expect(perError, perError?.message).toBeNull();

        await generateTuitionCharges(supabase, {
            orgId: ORG, periodKey: ATTRIBUTION_PERIOD, actorUserId: ACTOR,
            opportunityCustomerMemberIds: kids.map((k) => k.ocmId), today: `${ATTRIBUTION_PERIOD}-01`,
        });
        await applyFinancialReductions(supabase, {
            orgId: ORG, periodKey: ATTRIBUTION_PERIOD, actorUserId: ACTOR, customerIds: [customerId],
        });
        const reduction = (await reductionCharges(ATTRIBUTION_PERIOD))[0]! as { id: string };
        expect(reduction, "a reduction must exist to post").toBeTruthy();
        await postChildcareCharge(supabase, { orgId: ORG, chargeId: reduction.id, actorUserId: ACTOR } as never);

        const { data: journal } = await supabase
            .from("financial_journal_entries")
            .select("id, accounting_period_key, obligation_delta_cents, source_type, source_id")
            .eq("org_id", ORG)
            .eq("source_id", reduction.id);
        const rows = (journal ?? []) as Array<Record<string, unknown>>;
        expect(rows.length, "posting a reduction must report into the journal").toBeGreaterThan(0);
        expect(rows[0]!.accounting_period_key).toBe("FY2029-P08");
        // It moved the obligation the OTHER way — a reduction is negative money owed, and
        // `obligation_delta_cents` is the signed column that says so.
        expect(Number(rows[0]!.obligation_delta_cents)).toBeLessThan(0);
    }, 240_000);

    // ── 7 · MANUAL CREDITS AND ADJUSTMENTS ──────────────────────────────────────────────────

    it("records a manual credit with its reason and provenance, and is harmless to retry", async () => {
        await clearReductions();
        const key = "fred:manual:cert-goodwill";
        const first = await applyManualReduction(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            customerId,
            customerMemberId: kids[0]!.memberId,
            chargeCategory: "credit",
            amountCents: -7_500,
            reason: "Closure week in April — goodwill agreed with the director",
            effectiveDate: PERIOD_START,
            actorUserId: ACTOR,
            idempotencyKey: key,
        });
        expect(first.idempotent).toBe(false);

        const apps = await applications();
        expect(apps).toHaveLength(1);
        expect(apps[0]!.reduction_kind).toBe("manual");
        expect(apps[0]!.reason).toContain("Closure week");
        expect(apps[0]!.created_by).toBe(ACTOR);
        expect(Number(apps[0]!.amount_cents)).toBe(-7_500);

        const second = await applyManualReduction(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            chargeCategory: "credit",
            amountCents: -7_500,
            reason: "Closure week in April — goodwill agreed with the director",
            effectiveDate: PERIOD_START,
            actorUserId: ACTOR,
            idempotencyKey: key,
        });
        expect(second.idempotent, "a double submit is one credit").toBe(true);
        expect(second.chargeId).toBe(first.chargeId);
        expect(await applications()).toHaveLength(1);
    }, 180_000);

    it("refuses a manual reduction with no reason", async () => {
        await expect(
            applyManualReduction(supabase, {
                orgId: ORG,
                enrollmentAgreementId: kids[0]!.agreementId,
                chargeCategory: "credit",
                amountCents: -1_000,
                reason: "  ",
                effectiveDate: PERIOD_START,
                actorUserId: ACTOR,
                idempotencyKey: "fred:manual:cert-noreason",
            }),
        ).rejects.toThrow(/why/i);
    }, 120_000);

    it("reverses a manual credit by appending, leaving the original exactly as it was", async () => {
        await clearReductions();
        const original = await applyManualReduction(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            customerId,
            customerMemberId: kids[0]!.memberId,
            chargeCategory: "credit",
            amountCents: -7_500,
            reason: "Applied for the closure week",
            effectiveDate: PERIOD_START,
            actorUserId: ACTOR,
            idempotencyKey: "fred:manual:cert-reversible",
        });

        const reversal = await reverseManualReduction(supabase, {
            orgId: ORG,
            applicationId: original.applicationId,
            reason: "Applied to the wrong family",
            actorUserId: ACTOR,
        });
        expect(reversal.amountCents).toBe(7_500);

        const apps = await applications();
        expect(apps).toHaveLength(2);
        const originalRow = apps.find((a) => a.id === original.applicationId)!;
        expect(Number(originalRow.amount_cents), "the original is untouched").toBe(-7_500);
        expect(originalRow.reversed_by_id).toBe(reversal.applicationId);
        const reversalRow = apps.find((a) => a.id === reversal.applicationId)!;
        expect(reversalRow.reverses_id).toBe(original.applicationId);

        // ONE reversal. A second would credit the family twice for one decision.
        await expect(
            reverseManualReduction(supabase, {
                orgId: ORG, applicationId: original.applicationId, reason: "Again", actorUserId: ACTOR,
            }),
        ).rejects.toThrow(/already been reversed/i);
    }, 180_000);

    // ── 8 · VACATION CREDIT — THE SEAM, AND THE OWNER THAT DOES NOT EXIST ───────────────────

    it("has a vacation-credit policy seam and no authoritative entitlement source behind it", async () => {
        /*
         * `financial_policies.policy_type` already admits `vacation_credit`, so the POLICY seam is
         * real and a tenant can author one today. What does not exist anywhere in this schema is the
         * upstream fact a vacation credit must be computed from: an entitlement (how many days a
         * family gets), a notice rule, and an APPROVED absence. `child_attendance_events` records
         * that a child was absent; it does not record that the absence was an approved vacation day
         * drawn against an allowance.
         *
         * Thread 10 therefore ships the seam and names the gap rather than inventing an entitlement
         * model inside Billing, which would put a childcare attendance concern in the money domain
         * and make the wrong system its owner.
         */
        const { error } = await supabase.from("financial_policies").upsert({
            org_id: ORG,
            policy_type: "vacation_credit",
            scope_type: "org",
            value: { days_per_year: 10, basis: "daily_rate", requires_approved_absence: true },
            effective_start: "2026-01-01",
            is_active: true,
        });
        expect(error, "the vacation-credit policy seam must accept an authored policy").toBeNull();

        const tables = ["vacation_entitlements", "child_absences", "absence_approvals", "time_off_entitlements"];
        for (const table of tables) {
            const { error: probe } = await supabase.from(table).select("id").limit(1);
            expect(probe, `no authoritative source for vacation entitlement: ${table} does not exist`).toBeTruthy();
        }

        await supabase.from("financial_policies").delete().eq("org_id", ORG).eq("policy_type", "vacation_credit");
    }, 120_000);

    // ── 8 · SLICE 5C: THE SCENARIOS THE OPERATOR SURFACE RESTS ON ───────────────────────────

    /*
     * B — AN ADJUSTMENT CAN GO THE OTHER WAY. `credit` only ever lowers an obligation, but
     * `adjustment` is the category that corrects in either direction, and a positive amount is how
     * the canonical model says "owed again". Proving it here is what lets the panel offer a
     * direction at all rather than guessing.
     */
    it("records an adjustment that RAISES what is owed, and says so in its sign", async () => {
        await clearReductions();
        const raised = await applyManualReduction(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            customerId,
            customerMemberId: kids[0]!.memberId,
            chargeCategory: "adjustment",
            amountCents: 4_200,
            reason: "Correcting a credit that was applied twice",
            effectiveDate: PERIOD_START,
            actorUserId: ACTOR,
            idempotencyKey: "fred:manual:cert-raise",
        });
        const apps = await applications();
        expect(apps).toHaveLength(1);
        expect(Number(apps[0]!.amount_cents), "a positive amount is money owed again").toBe(4_200);
        expect(apps[0]!.reduction_kind).toBe("manual");
        expect(raised.amountCents).toBe(4_200);
    }, 180_000);

    /* D — ONE REVERSAL. A second would credit the family twice for one decision. */
    it("refuses a second reversal of the same adjustment", async () => {
        await clearReductions();
        const original = await applyManualReduction(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            customerId,
            customerMemberId: kids[0]!.memberId,
            chargeCategory: "credit",
            amountCents: -3_000,
            reason: "Goodwill for a closure day",
            effectiveDate: PERIOD_START,
            actorUserId: ACTOR,
            idempotencyKey: "fred:manual:cert-once",
        });
        await reverseManualReduction(supabase, {
            orgId: ORG,
            applicationId: original.applicationId,
            reason: "Recorded against the wrong enrolment",
            actorUserId: ACTOR,
        });
        await expect(
            reverseManualReduction(supabase, {
                orgId: ORG,
                applicationId: original.applicationId,
                reason: "Trying again",
                actorUserId: ACTOR,
            }),
        ).rejects.toThrow(/already been reversed/i);

        // And the ledger still holds exactly two rows: the decision and its opposite.
        const apps = await applications();
        expect(apps).toHaveLength(2);
    }, 240_000);

    /* H — another organisation's reduction is not this one's to reverse. */
    it("will not reverse a reduction that belongs to another organisation", async () => {
        await clearReductions();
        const mine = await applyManualReduction(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            customerId,
            customerMemberId: kids[0]!.memberId,
            chargeCategory: "credit",
            amountCents: -1_500,
            reason: "Goodwill",
            effectiveDate: PERIOD_START,
            actorUserId: ACTOR,
            idempotencyKey: "fred:manual:cert-crossorg",
        });
        await expect(
            reverseManualReduction(supabase, {
                orgId: "00000000-0000-4000-8000-0000000000ff",
                applicationId: mine.applicationId,
                reason: "Reaching across a tenant boundary",
                actorUserId: ACTOR,
            }),
        ).rejects.toThrow(/no such reduction/i);

        // Absent, not forbidden — and nothing moved.
        const apps = await applications();
        expect(apps).toHaveLength(1);
        expect(apps[0]!.reversed_by_id, "it was not reversed").toBeNull();
    }, 180_000);

    /*
     * E / F / G — ISOLATION. A decision about what a family owes is not a movement of money. It
     * writes no receipt, no refund and nothing a payment processor would hear about.
     */
    it("touches no receipt, no refund and no processor", async () => {
        await clearReductions();
        const before = await supabase
            .from("payments")
            .select("id, amount_cents, status, direction, processor, processor_transaction_id, refunds_payment_id")
            .eq("org_id", ORG);
        const beforeRows = JSON.stringify((before.data ?? []).slice().sort());

        const credit = await applyManualReduction(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            customerId,
            customerMemberId: kids[0]!.memberId,
            chargeCategory: "credit",
            amountCents: -2_500,
            reason: "Goodwill for a closure day",
            effectiveDate: PERIOD_START,
            actorUserId: ACTOR,
            idempotencyKey: "fred:manual:cert-isolation",
        });
        await reverseManualReduction(supabase, {
            orgId: ORG,
            applicationId: credit.applicationId,
            reason: "Reversing to prove isolation",
            actorUserId: ACTOR,
        });

        const after = await supabase
            .from("payments")
            .select("id, amount_cents, status, direction, processor, processor_transaction_id, refunds_payment_id")
            .eq("org_id", ORG);
        expect(JSON.stringify((after.data ?? []).slice().sort()), "payments are untouched").toBe(beforeRows);

        const { data: allocations } = await supabase
            .from("payment_allocations")
            .select("id")
            .eq("org_id", ORG)
            .eq("status", "active");
        expect(Array.isArray(allocations), "allocations are still readable").toBe(true);
    }, 240_000);

    /*
     * I — COLD REREAD, through the reader the operator surface actually uses. The card must be able
     * to reconstruct both the decision and its reversal from persistence alone, with the lineage
     * that tells them apart — otherwise it cannot offer a reversal, or know one already happened.
     */
    it("reads back both the decision and its reversal, with lineage", async () => {
        await clearReductions();
        const original = await applyManualReduction(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            customerId,
            customerMemberId: kids[0]!.memberId,
            chargeCategory: "credit",
            amountCents: -6_000,
            reason: "Closure week goodwill",
            effectiveDate: PERIOD_START,
            actorUserId: ACTOR,
            idempotencyKey: "fred:manual:cert-reread",
        });

        const before = await readAccountReductions(supabase, {
            orgId: ORG,
            agreementIds: [kids[0]!.agreementId],
        });
        expect(before, "the decision is readable on its own").toHaveLength(1);
        expect(before[0]!.applicationId).toBe(original.applicationId);
        expect(before[0]!.kind).toBe("manual");
        expect(before[0]!.category, "the category comes from the charge it wrote").toBe("credit");
        expect(before[0]!.amountCents).toBe(-6_000);
        expect(before[0]!.reason).toContain("Closure week");
        expect(before[0]!.reversedByApplicationId, "not yet reversed").toBeNull();

        const reversal = await reverseManualReduction(supabase, {
            orgId: ORG,
            applicationId: original.applicationId,
            reason: "Applied against the wrong enrolment",
            actorUserId: ACTOR,
        });

        const after = await readAccountReductions(supabase, {
            orgId: ORG,
            agreementIds: [kids[0]!.agreementId],
        });
        expect(after, "both rows survive — nothing is edited away").toHaveLength(2);
        const originalAfter = after.find((r) => r.applicationId === original.applicationId)!;
        const reversalAfter = after.find((r) => r.applicationId === reversal.applicationId)!;

        expect(originalAfter.amountCents, "the original is exactly as it was").toBe(-6_000);
        expect(originalAfter.reversedByApplicationId, "and now points at its reversal")
            .toBe(reversal.applicationId);
        expect(reversalAfter.amountCents, "the opposite was appended").toBe(6_000);
        expect(reversalAfter.reversesApplicationId, "and names what it undoes").toBe(original.applicationId);
        expect(reversalAfter.category, "a reversal is recorded as an adjustment").toBe("adjustment");

        // The two net to zero: what the family owes is back where it started.
        expect(after.reduce((n, r) => n + r.amountCents, 0)).toBe(0);
    }, 300_000);

    /* Only manual decisions are offered for reversal; authored policy is not anybody's to undo. */
    it("reads policy applications for context but never as manual decisions", async () => {
        const rows = await readAccountReductions(supabase, {
            orgId: ORG,
            agreementIds: kids.map((k) => k.agreementId),
        });
        for (const r of rows) {
            expect(["manual", "policy"]).toContain(r.kind);
        }
        expect(rows.every((r) => r.agreementId !== null), "every row names the enrolment it is against")
            .toBe(true);
    }, 120_000);

    /**
     * A CREDIT THAT NAMES NOTHING REDUCES NOTHING.
     *
     * `resolveAllocatableNet` nets a charge as its amount plus the reductions whose
     * `source_charge_id` names it. A manual reduction written without one still appears as a credit
     * row — so the card's signed reconciliation nets it and the family looks like they owe less —
     * while the obligation it was meant to reduce is untouched, and every authority that asks "what
     * is still collectible on this charge" answers the full amount.
     *
     * Two readings of the same household, and only one of them can be right. This pins the
     * difference so the surface cannot quietly go back to writing unattached credits.
     */
    it("only reduces an obligation when the reduction names the charge it reduces", async () => {
        await clearReductions();
        await clearTuition();
        await generateGross();
        const charges = await grossCharges();
        const target = charges[0]!;
        const grossCents = Number(target.amount_cents);

        const before = await resolveAllocatableNet(supabase, { orgId: ORG, chargeId: target.id });
        expect(before.netCents, "the charge starts at its full amount").toBe(grossCents);

        // Unattached: the shape the manual panel produced.
        await applyManualReduction(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            customerId,
            customerMemberId: kids[0]!.memberId,
            chargeCategory: "credit",
            amountCents: -5_000,
            reason: "Goodwill that names no charge",
            effectiveDate: PERIOD_START,
            actorUserId: ACTOR,
            idempotencyKey: "fred:manual:cert-unattached",
        });
        const afterFloating = await resolveAllocatableNet(supabase, { orgId: ORG, chargeId: target.id });
        expect(
            afterFloating.netCents,
            "a credit that names no charge leaves every obligation exactly as it was",
        ).toBe(grossCents);

        // Attached: the same decision, against the charge it is about.
        await applyManualReduction(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            customerId,
            customerMemberId: kids[0]!.memberId,
            chargeCategory: "credit",
            amountCents: -5_000,
            reason: "Goodwill against the tuition it concerns",
            effectiveDate: PERIOD_START,
            sourceChargeId: target.id,
            actorUserId: ACTOR,
            idempotencyKey: "fred:manual:cert-attached",
        });
        const afterAttached = await resolveAllocatableNet(supabase, { orgId: ORG, chargeId: target.id });
        expect(
            afterAttached.netCents,
            "naming the charge is what makes the credit reduce it",
        ).toBe(grossCents - 5_000);
    }, 300_000);

    /**
     * AND REVERSING AN ATTACHED CREDIT MUST GIVE THE OBLIGATION BACK.
     *
     * `reverseManualReduction` appends the opposite with `sourceChargeId` set to the ORIGINAL
     * REDUCTION'S OWN charge — not to the obligation the reduction was against. If that is what
     * reaches `financial_reduction_applications.source_charge_id`, the reversal names the credit
     * rather than the charge, `resolveAllocatableNet` never sees it, and the obligation stays
     * reduced after the operator has undone the reduction.
     */
    it("gives the obligation back when an attached credit is reversed", async () => {
        await clearReductions();
        await clearTuition();
        await generateGross();
        const target = (await grossCharges())[0]!;
        const grossCents = Number(target.amount_cents);

        const credit = await applyManualReduction(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            customerId,
            customerMemberId: kids[0]!.memberId,
            chargeCategory: "credit",
            amountCents: -5_000,
            reason: "Goodwill against this tuition",
            effectiveDate: PERIOD_START,
            sourceChargeId: target.id,
            actorUserId: ACTOR,
            idempotencyKey: "fred:manual:cert-attached-reverse",
        });
        expect((await resolveAllocatableNet(supabase, { orgId: ORG, chargeId: target.id })).netCents)
            .toBe(grossCents - 5_000);

        await reverseManualReduction(supabase, {
            orgId: ORG,
            applicationId: credit.applicationId,
            reason: "Reversing the goodwill",
            actorUserId: ACTOR,
        });

        expect(
            (await resolveAllocatableNet(supabase, { orgId: ORG, chargeId: target.id })).netCents,
            "undoing the reduction must restore the obligation it reduced",
        ).toBe(grossCents);
    }, 300_000);

    // ── 9 · REDUCTION / COLLECTIBILITY CONVERGENCE ──────────────────────────────────────────

    /**
     * A CREDIT AND ITS REVERSAL MUST BE A NO-OP, AND MUST BE ONE EVERY TIME.
     *
     * Driven on a clean obligation rather than on a shared tenant's history, because the question is
     * whether the cycle nets — and a fixture that earlier runs have already driven below zero cannot
     * answer it. Read back through `resolveAllocatableNet`, which is the net every authority that
     * asks "what does this charge still owe" is composed from.
     */
    it("nets a credit and its reversal to nothing, repeatedly, on one obligation", async () => {
        await clearReductions();
        await clearTuition();
        await generateGross();
        const target = (await grossCharges())[0]!;
        const gross = Number(target.amount_cents);

        const net = async () =>
            (await resolveAllocatableNet(supabase, { orgId: ORG, chargeId: target.id })).netCents;

        expect(await net(), "the obligation starts whole").toBe(gross);

        for (const cycle of [1, 2, 3]) {
            const credit = await applyManualReduction(supabase, {
                orgId: ORG,
                enrollmentAgreementId: kids[0]!.agreementId,
                customerId,
                customerMemberId: kids[0]!.memberId,
                chargeCategory: "credit",
                amountCents: -5_000,
                reason: `Goodwill, cycle ${cycle}`,
                effectiveDate: PERIOD_START,
                sourceChargeId: target.id,
                actorUserId: ACTOR,
                idempotencyKey: `fred:manual:cert-cycle-${cycle}`,
            });
            expect(await net(), `cycle ${cycle}: the credit reduces the obligation once`)
                .toBe(gross - 5_000);

            await reverseManualReduction(supabase, {
                orgId: ORG,
                applicationId: credit.applicationId,
                reason: `Undoing cycle ${cycle}`,
                actorUserId: ACTOR,
            });
            expect(await net(), `cycle ${cycle}: undoing it restores the obligation exactly`)
                .toBe(gross);
        }

        // Three complete cycles, and the obligation is exactly where it started. No ratchet.
        expect(await net(), "no drift across repeated cycles").toBe(gross);
    }, 420_000);

    /**
     * THE BOUNDARY: a reduction may not take more than the obligation holds.
     *
     * `resolveAllocatableNet` refuses to net an obligation below zero, and says that state is
     * unreachable because the policy path clamps. The manual path did not clamp or bound, so an
     * operator could write a credit larger than the charge it names and leave that obligation in a
     * state one authority refuses to read while others carried on reporting it. The writer now holds
     * the same bound, so the refusal is genuinely unreachable rather than merely undocumented.
     */
    it("refuses a manual reduction larger than the obligation it names", async () => {
        await clearReductions();
        await clearTuition();
        await generateGross();
        const target = (await grossCharges())[0]!;
        const gross = Number(target.amount_cents);

        await expect(
            applyManualReduction(supabase, {
                orgId: ORG,
                enrollmentAgreementId: kids[0]!.agreementId,
                customerId,
                customerMemberId: kids[0]!.memberId,
                chargeCategory: "credit",
                amountCents: -(gross + 1_000),
                reason: "More goodwill than there was obligation",
                effectiveDate: PERIOD_START,
                sourceChargeId: target.id,
                actorUserId: ACTOR,
                idempotencyKey: "fred:manual:cert-overreduce",
            }),
            "the writer refuses rather than leaving an obligation nobody can read",
        ).rejects.toThrow(/larger than what the charge still holds/i);

        // Nothing was written, and the obligation is still readable and whole.
        expect((await resolveAllocatableNet(supabase, { orgId: ORG, chargeId: target.id })).netCents)
            .toBe(gross);

        // Reducing it exactly to zero is allowed — the bound is "not below", not "not to".
        await applyManualReduction(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            customerId,
            customerMemberId: kids[0]!.memberId,
            chargeCategory: "credit",
            amountCents: -gross,
            reason: "Forgiving the whole charge",
            effectiveDate: PERIOD_START,
            sourceChargeId: target.id,
            actorUserId: ACTOR,
            idempotencyKey: "fred:manual:cert-exact",
        });
        expect(
            (await resolveAllocatableNet(supabase, { orgId: ORG, chargeId: target.id })).netCents,
            "an obligation reduced to exactly nothing is still readable",
        ).toBe(0);

        // And one more cent is refused, now that nothing remains.
        await expect(
            applyManualReduction(supabase, {
                orgId: ORG,
                enrollmentAgreementId: kids[0]!.agreementId,
                customerId,
                customerMemberId: kids[0]!.memberId,
                chargeCategory: "credit",
                amountCents: -1,
                reason: "One cent past nothing",
                effectiveDate: PERIOD_START,
                sourceChargeId: target.id,
                actorUserId: ACTOR,
                idempotencyKey: "fred:manual:cert-onemore",
            }),
        ).rejects.toThrow(/larger than what the charge still holds/i);
    }, 420_000);

    // ── 10 · CORE CLOSURE: RESPONSIBILITY, EXPECTED FUNDING, REFUND ─────────────────────────

    /**
     * These three are the remaining non-subsidy checkpoints. They run against the same clean
     * fixture the reduction cases use — reseeded per case — because the last false diagnosis in this
     * thread came from a household that had quietly accumulated state across runs.
     *
     * Every figure is read back from the canonical reader that owns it. Nothing here recomputes a
     * balance: an oracle that did would just be a second opinion about money.
     */

    /**
     * A household with no responsibility decisions on it.
     *
     * These cases each author an arrangement effective on the same day, and the service rightly
     * refuses to supersede an arrangement that starts on or after the date being asked for. Without
     * a reset the second case fails on the first case's leftovers — the accumulation that produced a
     * false diagnosis earlier in this thread, in miniature.
     */
    async function clearArrangements() {
        const { data: arrangementRows } = await supabase
            .from("financial_responsibility_arrangements")
            .select("id")
            .eq("org_id", ORG)
            .eq("customer_id", customerId);
        const arrangementIds = ((arrangementRows ?? []) as Array<{ id: string }>).map((r) => r.id);
        if (arrangementIds.length === 0) return;

        const { data: shareRows } = await supabase
            .from("financial_responsibility_shares")
            .select("id")
            .eq("org_id", ORG)
            .in("arrangement_id", arrangementIds);
        const shareIds = ((shareRows ?? []) as Array<{ id: string }>).map((r) => r.id);

        if (shareIds.length > 0) {
            await supabase.from("financial_expected_funding").delete().eq("org_id", ORG).in("share_id", shareIds);
        }
        await supabase.from("financial_responsibility_allocations").delete().eq("org_id", ORG).in("arrangement_id", arrangementIds);
        await supabase.from("financial_responsibility_shares").delete().eq("org_id", ORG).in("arrangement_id", arrangementIds);
        await supabase.from("financial_responsibility_arrangements").delete().eq("org_id", ORG).in("id", arrangementIds);
    }

    /** A person on this household, which is what a responsible party is. */
    async function aResponsibleParty(): Promise<string> {
        const { data } = await supabase
            .from("customer_persons")
            .select("person_id")
            .eq("org_id", ORG)
            .eq("customer_id", customerId)
            .limit(2);
        const rows = (data ?? []) as Array<{ person_id: string }>;
        expect(rows.length, "the household needs a person to be responsible").toBeGreaterThan(0);
        return rows[0]!.person_id;
    }

    it("RESPONSIBILITY · says who owes, and moves no money doing it", async () => {
        await clearArrangements();
        await clearReductions();
        await clearTuition();
        await generateGross();
        const charge = (await grossCharges())[0]!;
        const gross = Number(charge.amount_cents);
        const party = await aResponsibleParty();

        const before = {
            net: (await resolveAllocatableNet(supabase, { orgId: ORG, chargeId: charge.id })).netCents,
            balance: (await readChargeBalance(supabase, ORG, charge.id)).outstandingCents,
        };

        const half = Math.floor(gross / 2);
        await configureResponsibilityArrangement(supabase, {
            orgId: ORG,
            customerId,
            customerMemberId: kids[0]!.memberId,
            effectiveStart: PERIOD_START,
            shares: [{ responsiblePartyId: party, method: "fixed", amountCents: half }],
            actorUserId: ACTOR,
        });

        /*
         * ── ASK THE GRAIN YOU WROTE ──────────────────────────────────────────────────────────
         *
         * These reads used to pass no member and still get a child-scoped arrangement back, which
         * is the exact defect Financials 11B closed: an account-grain question answered with one
         * child's arrangement, presented to the operator as the account's. The write above is
         * child-scoped, so the read is too.
         */
        const arrangement = await readAccountArrangement(supabase, { orgId: ORG, customerId, customerMemberId: kids[0]!.memberId });
        expect(arrangement, "the arrangement is readable").toBeTruthy();
        /* And the rule itself: the household is NOT governed by one child's decision. */
        expect(
            await readAccountArrangement(supabase, { orgId: ORG, customerId }),
            "a child-scoped arrangement is not the account's",
        ).toBeNull();
        expect(arrangement!.shares.length, "it carries the party it was given").toBeGreaterThan(0);
        const share = arrangement!.shares.find((sh) => sh.responsiblePartyId === party)!;
        expect(share, "and that party is on it").toBeTruthy();
        expect(share.amountCents, "with the cents it was given").toBe(half);

        /*
         * RESPONSIBILITY ANSWERS WHO OWES. It is not a payment, not a reduction, and not a change to
         * what is owed — so nothing about the money may have moved because of it.
         */
        expect(
            (await resolveAllocatableNet(supabase, { orgId: ORG, chargeId: charge.id })).netCents,
            "the obligation is untouched by deciding who owes it",
        ).toBe(before.net);
        expect(
            (await readChargeBalance(supabase, ORG, charge.id)).outstandingCents,
            "and so is the balance",
        ).toBe(before.balance);
    }, 420_000);

    it("RESPONSIBILITY · a later arrangement supersedes rather than doubling", async () => {
        await clearArrangements();
        await clearReductions();
        await clearTuition();
        await generateGross();
        const party = await aResponsibleParty();

        await configureResponsibilityArrangement(supabase, {
            orgId: ORG, customerId, customerMemberId: kids[0]!.memberId,
            effectiveStart: PERIOD_START,
            shares: [{ responsiblePartyId: party, method: "fixed", amountCents: 60_000 }],
            actorUserId: ACTOR,
        });
        await configureResponsibilityArrangement(supabase, {
            orgId: ORG, customerId, customerMemberId: kids[0]!.memberId,
            effectiveStart: "2029-04-15",
            shares: [{ responsiblePartyId: party, method: "fixed", amountCents: 40_000 }],
            actorUserId: ACTOR,
        });

        const current = await readAccountArrangement(supabase, { orgId: ORG, customerId, customerMemberId: kids[0]!.memberId });
        expect(current, "there is a current arrangement").toBeTruthy();
        const amounts = current!.shares.map((sh) => sh.amountCents);
        expect(amounts, "the later decision is the one in force").toContain(40_000);
        expect(
            amounts.reduce((n, v) => (n ?? 0) + (v ?? 0), 0),
            "and the earlier one is history, not an addition to it",
        ).toBe(40_000);

        // The predecessor still exists as a record of what was decided before.
        const { data: all } = await supabase
            .from("financial_responsibility_arrangements")
            .select("id, effective_start, effective_end")
            .eq("org_id", ORG)
            .eq("customer_id", customerId);
        expect((all ?? []).length, "the earlier arrangement is not deleted").toBeGreaterThan(1);
    }, 420_000);

    /**
     * EXPECTED FUNDING IS NOT SUBSIDY, AND NOT MONEY.
     *
     * It is exercised here with an employer sponsorship precisely to show it needs no subsidy
     * authorization, claim or remittance: it is an expectation attached to a responsibility share.
     * It must not move a balance, and must not make anything less collectible merely by existing.
     */
    it("EXPECTED FUNDING · is an expectation, not a receipt, and suppresses nothing", async () => {
        await clearArrangements();
        await clearReductions();
        await clearTuition();
        await generateGross();
        const charge = (await grossCharges())[0]!;
        const party = await aResponsibleParty();

        const arrangementId = (await configureResponsibilityArrangement(supabase, {
            orgId: ORG, customerId, customerMemberId: kids[0]!.memberId,
            effectiveStart: PERIOD_START,
            shares: [{ responsiblePartyId: party, method: "fixed", amountCents: 100_000 }],
            actorUserId: ACTOR,
        })) as unknown as { id?: string };

        const before = {
            net: (await resolveAllocatableNet(supabase, { orgId: ORG, chargeId: charge.id })).netCents,
            outstanding: (await readChargeBalance(supabase, ORG, charge.id)).outstandingCents,
            collectible: (await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId: charge.id })),
        };

        const arrangement = await readAccountArrangement(supabase, { orgId: ORG, customerId, customerMemberId: kids[0]!.memberId });
        const shareId = arrangement!.shares.find((sh) => sh.responsiblePartyId === party)!.id;

        await configureExpectedFunding(supabase, {
            orgId: ORG,
            shareId,
            arrangementId: arrangement!.id ?? (arrangementId?.id ?? null),
            fundingSourceType: "employer_sponsorship",
            fundingSourceLabel: "Certification Employer Sponsorship",
            basis: "fixed_amount",
            expectedAmountCents: 75_000,
            effectiveStart: PERIOD_START,
            idempotencyKey: "fred:funding:cert-expected",
            actorUserId: ACTOR,
        });

        const withFunding = await readAccountArrangement(supabase, { orgId: ORG, customerId, customerMemberId: kids[0]!.memberId });
        const funded = withFunding!.shares.find((sh) => sh.responsiblePartyId === party)!;
        expect(funded.expectedFunding.length, "the expectation is recorded on the share").toBeGreaterThan(0);

        // EXPECTED is not RECEIVED, and not a suppression.
        expect(
            (await resolveAllocatableNet(supabase, { orgId: ORG, chargeId: charge.id })).netCents,
            "expecting money from somebody else does not reduce the obligation",
        ).toBe(before.net);
        expect(
            (await readChargeBalance(supabase, ORG, charge.id)).outstandingCents,
            "nor what is outstanding",
        ).toBe(before.outstanding);
        const after = await resolveFamilyCollectible(supabase, { orgId: ORG, chargeId: charge.id });
        expect(
            after.currentlyCollectibleCents,
            "and an expectation alone suppresses nothing",
        ).toBe(before.collectible.currentlyCollectibleCents);
    }, 420_000);

    it("EXPECTED FUNDING · a correction supersedes rather than adding", async () => {
        await clearArrangements();
        await clearReductions();
        await clearTuition();
        await generateGross();
        const party = await aResponsibleParty();
        await configureResponsibilityArrangement(supabase, {
            orgId: ORG, customerId, customerMemberId: kids[0]!.memberId,
            effectiveStart: PERIOD_START,
            shares: [{ responsiblePartyId: party, method: "fixed", amountCents: 100_000 }],
            actorUserId: ACTOR,
        });
        const arrangement = await readAccountArrangement(supabase, { orgId: ORG, customerId, customerMemberId: kids[0]!.memberId });
        const shareId = arrangement!.shares.find((sh) => sh.responsiblePartyId === party)!.id;

        for (const [amount, key] of [[75_000, "a"], [70_000, "b"]] as const) {
            await configureExpectedFunding(supabase, {
                orgId: ORG, shareId, arrangementId: arrangement!.id,
                fundingSourceType: "employer_sponsorship",
                fundingSourceLabel: "Certification Employer Sponsorship",
                basis: "fixed_amount",
                expectedAmountCents: amount,
                effectiveStart: PERIOD_START,
                idempotencyKey: `fred:funding:cert-supersede-${key}`,
                actorUserId: ACTOR,
            });
        }

        const after = await readAccountArrangement(supabase, { orgId: ORG, customerId, customerMemberId: kids[0]!.memberId });
        const share = after!.shares.find((sh) => sh.responsiblePartyId === party)!;
        const total = share.expectedFunding.reduce((n, f) => n + (f.expectedAmountCents ?? 0), 0);
        expect(total, "the correction replaces the expectation rather than stacking on it").toBe(70_000);
    }, 420_000);

    /**
     * REFUND IS A NEW OUTBOUND PAYMENT, and the receipt it refunds is never touched.
     */
    it("REFUND · gives money back without rewriting what was received", async () => {
        await clearArrangements();
        await clearReductions();
        /*
         * ITS OWN OBLIGATION, not one of the shared tuition charges. Refunding requires posting and
         * settling a charge, and a posted charge cannot be cleaned up afterwards — so using the
         * tuition cohort would leave a settled charge behind that makes every later generation case
         * report `already_posted`. That is precisely the accumulation this thread has been bitten by.
         */
        const gross = 100_000;
        const draft = await createChildcareDraftCharge(supabase, {
            orgId: ORG,
            enrollmentAgreementId: kids[0]!.agreementId,
            chargeCategory: "fee",
            amountCents: gross,
            serviceDate: PERIOD_START,
            description: `Refund certification ${Date.now()}`,
            actorUserId: ACTOR,
        } as never);
        const charge = { id: (draft as { id: string }).id };
        await postChildcareCharge(supabase, { orgId: ORG, chargeId: charge.id, actorUserId: ACTOR } as never);

        const { payment } = await recordChildcarePayment(supabase, {
            orgId: ORG,
            billableSourceType: "enrollment_agreement",
            billableSourceId: kids[0]!.agreementId,
            customerId,
            amountCents: gross,
            paymentMethod: "check",
            actorUserId: ACTOR,
        });
        await applyPaymentToCharge(supabase, {
            orgId: ORG, paymentId: payment.id, chargeId: charge.id, amountCents: gross,
        });
        expect((await readChargeBalance(supabase, ORG, charge.id)).outstandingCents, "settled").toBe(0);

        const receiptBefore = await supabase
            .from("payments").select("amount_cents, direction, status, payment_method, received_at")
            .eq("org_id", ORG).eq("id", payment.id).maybeSingle();

        const refundResult = await refundChildcarePayment(supabase, {
            orgId: ORG, paymentId: payment.id, amountCents: gross,
            reason: "Certification refund", actorUserId: ACTOR,
            /*
             * KEYED TO THE RECEIPT, not to the case. A constant key is idempotent across RUNS as
             * well as within one, so the second run's refund silently returned the first run's and
             * asserted against a payment that no longer had anything to do with it. One refund
             * decision per receipt is the honest identity.
             */
            idempotencyKey: `fred:refund:cert-core:${payment.id}`,
        });

        const receiptAfter = await supabase
            .from("payments").select("amount_cents, direction, status, payment_method, received_at")
            .eq("org_id", ORG).eq("id", payment.id).maybeSingle();
        expect(JSON.stringify(receiptAfter.data), "the receipt reads exactly as it was received")
            .toBe(JSON.stringify(receiptBefore.data));

        const { data: refunds } = await supabase
            .from("payments").select("id, amount_cents, direction, reversal_origin")
            .eq("org_id", ORG).eq("refunds_payment_id", payment.id);
        expect((refunds ?? []).length, "exactly one outbound refund row").toBe(1);
        expect(refundResult.alreadyRefunded, "and it was made by this run, not returned from a past one")
            .toBe(false);
        expect((refunds as Array<{ direction: string }>)[0]!.direction).toBe("outbound");

        expect(
            await readPaymentRefundedCents(supabase, ORG, payment.id),
            "the refunded figure is what was given back",
        ).toBe(gross);
        expect(
            (await readChargeBalance(supabase, ORG, charge.id)).outstandingCents,
            "and the obligation is owed again, because the money went back",
        ).toBe(gross);
        expect(
            await readPaymentUnappliedCents(supabase, ORG, payment.id, gross),
            "refunded money is not unapplied money waiting to be used",
        ).toBe(0);
    }, 600_000);
});
