export const dynamic = "force-dynamic";

export default function AdminV2FinancePage() {
    return (
        <div className="w-full max-w-4xl space-y-3 pb-2">
            <header>
                <h1 className="text-xl font-semibold tracking-tight text-alloy-midnight">Finance</h1>
                <p className="mt-1 text-xs text-alloy-midnight/60">Coming next: AdminV2 finance navigation.</p>
            </header>
            <div className="rounded-xl border border-alloy-stone/15 bg-white/60 px-4 py-3 text-sm text-alloy-midnight/70">
                This area is not migrated to AdminV2 yet.
            </div>
            <a
                href="/adminV2/finance/obligation-review"
                className="block rounded-xl border border-alloy-stone/15 bg-white/60 px-4 py-3 text-sm text-alloy-midnight/80 transition hover:bg-alloy-stone/10"
            >
                <span className="font-medium text-alloy-midnight">Obligation review</span>
                <span className="mt-0.5 block text-xs text-alloy-midnight/60">
                    Pre-posting review of obligations generated by the consumption pipeline.
                </span>
            </a>
        </div>
    );
}

