CREATE TABLE IF NOT EXISTS public.processing_plan_operations (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    org_id uuid NOT NULL REFERENCES public.orgs (id) ON DELETE CASCADE,
    plan_id uuid NOT NULL REFERENCES public.processing_commit_plans (id) ON DELETE CASCADE,
    op_id text NOT NULL,
    op_order integer NOT NULL,
    op_kind text NOT NULL,
    command_key text NOT NULL,
    command_version text NOT NULL,
    target_type text NOT NULL,
    target_id uuid,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    before_snapshot jsonb,
    after_values jsonb,
    reason text,
    evidence_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
    resolution_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
    risk text NOT NULL DEFAULT 'low',
    depends_on jsonb NOT NULL DEFAULT '[]'::jsonb,
    atomic_group text,
    precondition_record_version text,
    included boolean NOT NULL DEFAULT true,
    optional boolean NOT NULL DEFAULT false,
    reversibility text NOT NULL DEFAULT 'reversible',
    expected_side_effects jsonb NOT NULL DEFAULT '[]'::jsonb,
    mapping jsonb,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT uq_processing_plan_operations_plan_op UNIQUE (plan_id, op_id)
);
