import type { WorkUnitWorkspaceModel } from "../workspace-types";

/**
 * Home cleaning — concrete lane: Unassigned jobs · east cluster (drill from Operations throughput rollup).
 */
export const demoCleaningWorkUnitBase: Omit<WorkUnitWorkspaceModel, "workspaceLevel"> = {
  workUnitId: "lane-unassigned-east",
  laneKey: "unassigned_jobs_east",
  focusLabel: "Operations · Throughput · Unassigned",
  aiSummary: {
    headline: "Unassigned jobs · east cluster",
    aiAwarenessLine: "7 jobs · east · SLA + coverage watch.",
    bodyParagraphs: [
      "2h assignment SLA breached on 2 jobs; deep clean needs dispatch before 13:00; east coverage thin ~90m.",
    ],
    emphasisPhrases: ["2h assignment SLA", "13:00"],
  },
  signals: [
    {
      id: "wu-s1",
      severity: "critical",
      title: "2 past assignment SLA",
      actions: [{ id: "sla_review", label: "Review" }],
    },
    {
      id: "wu-s2",
      severity: "warning",
      title: "Deep clean unassigned",
      actions: [{ id: "dispatch_deep_clean", label: "Dispatch" }],
    },
    {
      id: "wu-s3",
      severity: "warning",
      title: "East capacity low",
      actions: [{ id: "open_coverage", label: "Coverage" }],
    },
  ],
  kpis: [
    { id: "k-b1", label: "Jobs in queue", value: "7", lane: "business" },
    { id: "k-b2", label: "Avg wait", value: "47", unit: "m", lane: "business" },
    { id: "k-b3", label: "SLA breaches", value: "2", lane: "business" },
    { id: "k-a1", label: "Auto-assign confidence", value: "61", unit: "%", lane: "ai", aiSummary: "Holding low matches" },
    { id: "k-a2", label: "Route fit score", value: "0.72", lane: "ai" },
    { id: "k-a3", label: "Prediction confidence", value: "84", unit: "%", lane: "ai" },
  ],
  primaryQueue: {
    id: "queue-unassigned-east",
    title: "Unassigned jobs",
    countBadge: 7,
    sortCaption: "SLA risk ↓",
    workUnitGroupHeaders: {
      past_sla: { emoji: "🔴", label: "Past SLA" },
      hard_start: { emoji: "⚠️", label: "Hard start" },
      morning_wave: { label: "Morning wave" },
    },
    items: [
      {
        id: "job-7712",
        title: "Chen residence",
        subtitle: "1842 Magnolia Ln · standard clean",
        groupKey: "past_sla",
        urgencyTier: "critical",
        waitStatus: "breached",
        valueLabel: "$180",
        windowLabel: "10:00–12:00",
        routeLabel: "East · B7",
        waitCompact: "2h 14m",
        tags: ["standard", "recurring", "priority"],
        quickActions: [{ id: "assign_nearest", label: "Assign" }],
      },
      {
        id: "job-7704",
        title: "Torres — Airbnb turnover",
        subtitle: "220 Riverside TC · standard clean",
        groupKey: "past_sla",
        urgencyTier: "critical",
        waitStatus: "breached",
        valueLabel: "$320 recurring",
        windowLabel: "09:30–11:30",
        routeLabel: "East · B4",
        waitCompact: "2h 06m",
        tags: ["standard", "recurring", "first visit"],
        quickActions: [{ id: "pair_route", label: "Pair B7" }],
      },
      {
        id: "job-7720",
        title: "Nguyen deep clean",
        subtitle: "408 Brookridge Pkwy · deep clean",
        groupKey: "hard_start",
        urgencyTier: "warning",
        waitStatus: "approaching",
        valueLabel: "$1,200 job",
        windowLabel: "13:00–16:00",
        routeLabel: "East · D2",
        waitCompact: "48m",
        tags: ["deep clean", "2-person", "first visit"],
        quickActions: [{ id: "escalate_dispatch", label: "Escalate" }],
      },
      {
        id: "job-7724",
        title: "Patel move-out",
        subtitle: "19 Hawthorn · standard + windows",
        groupKey: "morning_wave",
        urgencyTier: "standard",
        waitStatus: "safe",
        windowLabel: "08:00–10:00",
        routeLabel: "East · A2",
        waitCompact: "22m",
        tags: ["standard", "recurring", "move-out"],
        quickActions: [{ id: "auto_assign_east", label: "Auto east" }],
      },
    ],
  },
  workSummary: {
    id: "wk-lane-east",
    title: "Lane automation",
    progressLabel: "4 workflows",
    workflowMetrics: {
      avgRunTimeLabel: "2m 10s",
      successRateLabel: "97.2%",
      runsTodayLabel: "412",
      failuresTodayLabel: "3",
    },
    workflowRuns: [
      { id: "wf-1", name: "Auto-assign queue", status: "running", lastRunLabel: "09:41 · 45s" },
      { id: "wf-2", name: "Dispatch optimizer", status: "running", lastRunLabel: "09:40 · queued" },
      { id: "wf-3", name: "SLA monitor", status: "completed", lastRunLabel: "09:38 · 12s" },
      { id: "wf-4", name: "Inventory cross-check", status: "completed", lastRunLabel: "09:12 · 3m 01s" },
    ],
    aiSuggestion: "Pair 7712 + 7704 on one east loop · ~18 min drive saved.",
  },
  actionsRail: {
    primaries: [],
    systemActions: [
      { id: "create_job", label: "Create job", variant: "primary" },
      { id: "ingest_document", label: "Ingest document", variant: "secondary" },
      { id: "execute_workflow", label: "Execute workflow", variant: "secondary" },
      { id: "run_report", label: "Run report", variant: "secondary" },
    ],
    quickOperations: [
      { id: "bulk_assign", label: "Bulk assign" },
      { id: "auto_assign", label: "Auto-assign" },
      { id: "notify_team", label: "Notify team" },
      { id: "export_queue", label: "Export queue" },
    ],
    smartSuggestions: [
      { id: "ai_assign_east", label: "Auto-assign east" },
      { id: "group_two_cleans", label: "Group 2 cleans" },
      { id: "escalate_deep_clean", label: "Escalate dispatch" },
    ],
    systemStatusLines: ["2 SLA breaches · steady load", "East coverage 78% · 90m"],
    overflow: [{ id: "lane_settings", label: "Lane settings" }],
  },
  contextRail: { groups: [] },
};
